Gin: PluginButton Class Reference
PluginButton Class Reference
Button for toggling a parameter.
Public Member Functions
PluginButton (Parameter *parameter_)
~PluginButton () override
void valueUpdated (Parameter *) override
void clicked () override
void parentHierarchyChanged () override
Public Attributes
Parameter * parameter
Detailed Description
Button for toggling a parameter.
Constructor & Destructor Documentation
PluginButton()
PluginButton::PluginButton (Parameter * parameter_)
References Parameter::addListener(), Parameter::getShortName(), Parameter::getUserValue(), Parameter::getUserValueText(), and parameter.
~PluginButton()
PluginButton::~PluginButton () override
References parameter, and Parameter::removeListener().
Member Function Documentation
valueUpdated()
void PluginButton::valueUpdated (Parameter *) override virtual
Implements Parameter::ParameterListener.
References Parameter::getUserValue(), Parameter::getUserValueText(), and parameter.
clicked()
void PluginButton::clicked () override
References Parameter::beginUserAction(), Parameter::endUserAction(), Parameter::getUserValue(), Parameter::getUserValueText(), parameter, and Parameter::setUserValueNotifingHost().
parentHierarchyChanged()
void PluginButton::parentHierarchyChanged () override
Member Data Documentation
parameter
Parameter* PluginButton::parameter
Referenced by clicked(), PluginButton(), valueUpdated(), and ~PluginButton().
The documentation for this class was generated from the following file:
gin_plugincomponents.h