Gin: SVGPluginButton Class Reference
SVGPluginButton Class Reference
gin_plugin » components
Button for toggling a parameter.
#include <gin_plugincomponents.h>
Public Member Functions
SVGPluginButton (Parameter *parameter_, const juce::String &svg)
~SVGPluginButton () override
void valueUpdated (Parameter *) override
void clicked () override
void parentHierarchyChanged () override
Public Member Functions inherited from SVGButton
SVGButton (const juce::String &name, const juce::String &rawSVG_, int inset_=0)
void setColour (juce::Colour c)
void clearColour ()
std::optional< juce::Colour > getColour () const
Public Attributes
Parameter * parameter
Public Attributes inherited from SVGButton
juce::String rawSVG
int inset = 0
std::optional< juce::Colour > colour
Detailed Description
Button for toggling a parameter.
Constructor & Destructor Documentation
SVGPluginButton()
SVGPluginButton::SVGPluginButton (Parameter * parameter_, const juce::String & svg)
References Parameter::addListener(), Parameter::getUserValue(), Parameter::getUserValueText(), and parameter.
~SVGPluginButton()
SVGPluginButton::~SVGPluginButton () override
References parameter, and Parameter::removeListener().
Member Function Documentation
valueUpdated()
void SVGPluginButton::valueUpdated (Parameter *) override virtual
Implements Parameter::ParameterListener.
References Parameter::getUserValue(), Parameter::getUserValueText(), and parameter.
clicked()
void SVGPluginButton::clicked () override
References Parameter::beginUserAction(), Parameter::endUserAction(), Parameter::getUserValue(), Parameter::getUserValueText(), parameter, and Parameter::setUserValueNotifingHost().
parentHierarchyChanged()
void SVGPluginButton::parentHierarchyChanged () override
Member Data Documentation
parameter
Parameter* SVGPluginButton::parameter
Referenced by clicked(), SVGPluginButton(), valueUpdated(), and ~SVGPluginButton().
The documentation for this class was generated from the following file:
gin_plugincomponents.h