Gin: Ellipse< T > Class Template Reference
Ellipse< T > Class Template Reference
Equations to calculate the shape of an ellipse and to calculate points on the edge of the ellipse and to see if points are inside or outside.
Public Member Functions
Ellipse (T a_, T b_)
bool isPointOn (Point< T > pt, T accuracy=0.00001)
bool isPointOutside (Point< T > pt)
bool isPointInside (Point< T > pt)
Point< T > pointAtAngle (T angle)
Public Attributes
T a = 0
T b = 0
Detailed Description
template<typename T>
class Ellipse< T >
Equations to calculate the shape of an ellipse and to calculate points on the edge of the ellipse and to see if points are inside or outside.
Constructor & Destructor Documentation
Ellipse()
template<typename T > Ellipse< T >::Ellipse (T a_, T b_)
Member Function Documentation
isPointOn()
template<typename T > bool Ellipse< T >::isPointOn (Point< T > pt, T accuracy = 0.00001)
References Ellipse< T >::a, Ellipse< T >::b, Point< T >::getX(), Point< T >::getY(), and square.
isPointOutside()
template<typename T > bool Ellipse< T >::isPointOutside (Point< T > pt)
References Ellipse< T >::a, Ellipse< T >::b, Point< T >::getX(), Point< T >::getY(), and square.
isPointInside()
template<typename T > bool Ellipse< T >::isPointInside (Point< T > pt)
References Ellipse< T >::a, Ellipse< T >::b, Point< T >::getX(), Point< T >::getY(), and square.
pointAtAngle()
template<typename T > Point<T> Ellipse< T >::pointAtAngle (T angle)
References Ellipse< T >::a, Ellipse< T >::b, and square.
Member Data Documentation
a
template<typename T > T Ellipse< T >::a = 0
Referenced by Ellipse< T >::isPointInside(), Ellipse< T >::isPointOn(), Ellipse< T >::isPointOutside(), and Ellipse< T >::pointAtAngle().
b
template<typename T > T Ellipse< T >::b = 0
Referenced by Ellipse< T >::isPointInside(), Ellipse< T >::isPointOn(), Ellipse< T >::isPointOutside(), and Ellipse< T >::pointAtAngle().
The documentation for this class was generated from the following file:
gin_geometry.h