Gin: StereoDelay Class Reference
StereoDelay Class Reference
gin_dsp » dsp
Stereo delay effect with feedback, cross-feedback, and wet/dry mix.
#include <gin_stereodelay.h>
Public Member Functions
StereoDelay (double maxDelay_=5.1)
void process (juce::AudioSampleBuffer &buffer)
void processSmoothed (juce::AudioSampleBuffer &buffer)
void setSampleRate (double sr)
void setParams (float delay_, float mix_, float feedback_, float crossfeed_)
void reset ()
Detailed Description
Stereo delay effect with feedback, cross-feedback, and wet/dry mix.
StereoDelay provides a professional stereo delay effect with independent left/right delay lines, feedback control, and ping-pong capability via cross-feedback. Parameters are smoothed to avoid zipper noise.
Key Features:
Independent stereo delay lines
Feedback control (repeats)
Cross-feedback (ping-pong delay effect)
Wet/dry mix control
Parameter smoothing for artifact-free automation
High-quality Lagrange interpolation
Parameters:
delay: Delay time in seconds
mix: Wet/dry mix (0.0 = dry, 1.0 = wet)
feedback: Amount of delayed signal fed back (0.0 to 0.99)
crossfeed: Amount of cross-channel feedback for ping-pong (0.0 to 0.99)
Usage:
StereoDelay delay(5.0); // Max 5 seconds delay
delay.setSampleRate(44100.0);
delay.setParams(0.5f, 0.5f, 0.6f, 0.3f);
// delay=0.5s, mix=50%, feedback=60%, crossfeed=30%
delay.processSmoothed(audioBuffer); // Smooth parameter changes
// or
delay.process(audioBuffer); // No smoothing (faster)
See also
DelayLine
Constructor & Destructor Documentation
StereoDelay()
StereoDelay::StereoDelay (double maxDelay_ = 5.1)
References setSampleRate().
Member Function Documentation
process()
void StereoDelay::process (juce::AudioSampleBuffer & buffer)
References DelayLine::readLagrange(), DelayLine::write(), and DelayLine::writeFinished().
Referenced by processSmoothed().
processSmoothed()
void StereoDelay::processSmoothed (juce::AudioSampleBuffer & buffer)
References process(), DelayLine::readLagrange(), DelayLine::write(), and DelayLine::writeFinished().
setSampleRate()
void StereoDelay::setSampleRate (double sr)
References DelayLine::setSize().
Referenced by StereoDelay().
setParams()
void StereoDelay::setParams (float delay_, float mix_, float feedback_, float crossfeed_)
reset()
void StereoDelay::reset ()
References DelayLine::clear().
The documentation for this class was generated from the following file:
gin_stereodelay.h