Gin: Point< T > Class Template Reference
Point< T > Class Template Reference
gin » utilities
A lightweight 2D point class for projects that don't use juce_graphics.
#include <gin_point.h>
Public Member Functions
Point ()=default
Creates a point at the origin (0, 0).
Point (T x_, T y_)
Creates a point with the specified coordinates.
T getX ()
Returns the x coordinate.
T getY ()
Returns the y coordinate.
Public Attributes
T x = T (0)
The x coordinate.
T y = T (0)
The y coordinate.
Detailed Description
template<typename T>
class Point< T >
A lightweight 2D point class for projects that don't use juce_graphics.
This class provides a simple coordinate pair with optional conversion to/from juce::Point when juce_graphics is available. It's useful for modules that need basic point functionality without depending on the full graphics module.
See also
getX, getY, toJuce
Constructor & Destructor Documentation
Point() [1/2]
template<typename T > Point< T >::Point () default
Creates a point at the origin (0, 0).
Referenced by Filter::getResponseMagnitude(), Point< T >::Point(), WTOscillator::processAddingComplex(), WTOscillator::processAddingCrossfadeComplex(), WTOscillator::processAddingSimple(), and Filter::setNumChannels().
Point() [2/2]
template<typename T > Point< T >::Point (T x_, T y_)
Creates a point with the specified coordinates.
Parameters
x_ The x coordinate
y_ The y coordinate
References Point< T >::Point(), Point< T >::x, and Point< T >::y.
Member Function Documentation
getX()
template<typename T > T Point< T >::getX ()
Returns the x coordinate.
Returns
The x coordinate
References Point< T >::x.
Referenced by gradientRect(), Ellipse< T >::isPointInside(), Ellipse< T >::isPointOn(), Ellipse< T >::isPointOutside(), and ModCurveButton::paintButton().
getY()
template<typename T > T Point< T >::getY ()
Returns the y coordinate.
Returns
The y coordinate
References Point< T >::y.
Referenced by gradientRect(), Ellipse< T >::isPointInside(), Ellipse< T >::isPointOn(), Ellipse< T >::isPointOutside(), and ModCurveButton::paintButton().
Member Data Documentation
x
template<typename T > T Point< T >::x = T (0)
The x coordinate.
Referenced by Object3D::addBox(), Vec3< T >::cross(), Vec3< T >::dot(), Point< T >::getX(), Ellipse< T >::isPointInside(), Ellipse< T >::isPointOn(), Ellipse< T >::isPointOutside(), Mat4< T >::lookAt(), Vec3< T >::operator+(), Vec3< T >::operator+=(), Vec3< T >::operator-(), Vec3< T >::operator-=(), Spline::Element::operator<(), Vec3< T >::operator==(), Camera3D::orbit(), Point< T >::Point(), Mat4< T >::project(), Mat4< T >::transformPoint(), Mat4< T >::transformVector(), and Mat4< T >::translation().
y
template<typename T > T Point< T >::y = T (0)
The y coordinate.
Referenced by Object3D::addBox(), Vec3< T >::cross(), Vec3< T >::dot(), Point< T >::getY(), Lagrange::interpolate(), Ellipse< T >::isPointInside(), Ellipse< T >::isPointOn(), Ellipse< T >::isPointOutside(), Mat4< T >::lookAt(), Vec3< T >::operator+(), Vec3< T >::operator+=(), Vec3< T >::operator-(), Vec3< T >::operator-=(), Vec3< T >::operator==(), Camera3D::orbit(), Point< T >::Point(), Mat4< T >::project(), Mat4< T >::transformPoint(), Mat4< T >::transformVector(), and Mat4< T >::translation().
The documentation for this class was generated from the following file:
gin_point.h