Gin: SamplePlayer Class Reference
SamplePlayer Class Reference
gin_dsp » dsp
#include <gin_sampleplayer.h>
Public Member Functions
SamplePlayer ()
SamplePlayer (const char *data, int dataLen)
SamplePlayer (const juce::File &f)
void load (const char *data, int dataLen)
void load (const juce::File &f)
void setBuffer (const juce::AudioSampleBuffer &newBuffer, double sampleRate)
void setPlaybackSampleRate (double sampleRate)
void reset ()
void setCrossfadeSamples (int samples)
void play ()
void stop ()
bool isPlaying () const
void setLooping (bool shouldLoop)
bool isLooping () const
void processBlock (juce::AudioSampleBuffer &output)
double getPosition () const
double getPositionInSeconds () const
void setPosition (double newPosition)
double getLengthInSeconds () const
bool hasFileLoaded () const
juce::File getLoadedFile () const
const juce::AudioSampleBuffer & getBuffer () const
double getSourceSampleRate () const
void clear ()
juce::AudioPlayHead::PositionInfo populatePositionInfo ()
Returns position info for use with an AudioPlayHead.
Constructor & Destructor Documentation
SamplePlayer() [1/3]
SamplePlayer::SamplePlayer ()
SamplePlayer() [2/3]
SamplePlayer::SamplePlayer (const char * data, int dataLen)
SamplePlayer() [3/3]
SamplePlayer::SamplePlayer (const juce::File & f)
Member Function Documentation
load() [1/2]
void SamplePlayer::load (const char * data, int dataLen)
Referenced by SampleFileComponent::filesDropped().
load() [2/2]
void SamplePlayer::load (const juce::File & f)
setBuffer()
void SamplePlayer::setBuffer (const juce::AudioSampleBuffer & newBuffer, double sampleRate)
setPlaybackSampleRate()
void SamplePlayer::setPlaybackSampleRate (double sampleRate)
Referenced by StandaloneAudioProcessorPlayer::audioDeviceAboutToStart().
reset()
void SamplePlayer::reset ()
setCrossfadeSamples()
void SamplePlayer::setCrossfadeSamples (int samples)
play()
void SamplePlayer::play ()
stop()
void SamplePlayer::stop ()
isPlaying()
bool SamplePlayer::isPlaying () const
Referenced by SampleFileComponent::timerCallback().
setLooping()
void SamplePlayer::setLooping (bool shouldLoop)
isLooping()
bool SamplePlayer::isLooping () const
processBlock()
void SamplePlayer::processBlock (juce::AudioSampleBuffer & output)
Referenced by StandaloneAudioProcessorPlayer::preProcessBlock().
getPosition()
double SamplePlayer::getPosition () const
Referenced by SampleFileComponent::timerCallback().
getPositionInSeconds()
double SamplePlayer::getPositionInSeconds () const
setPosition()
void SamplePlayer::setPosition (double newPosition)
getLengthInSeconds()
double SamplePlayer::getLengthInSeconds () const
hasFileLoaded()
bool SamplePlayer::hasFileLoaded () const
Referenced by StandaloneAudioProcessorPlayer::preProcessBlock(), and SampleFileComponent::timerCallback().
getLoadedFile()
juce::File SamplePlayer::getLoadedFile () const
getBuffer()
const juce::AudioSampleBuffer & SamplePlayer::getBuffer () const
Referenced by SampleFileComponent::filesDropped().
getSourceSampleRate()
double SamplePlayer::getSourceSampleRate () const
clear()
void SamplePlayer::clear ()
populatePositionInfo()
juce::AudioPlayHead::PositionInfo SamplePlayer::populatePositionInfo ()
Returns position info for use with an AudioPlayHead.
Call from the audio thread before processing.
Returns
PositionInfo populated with current playback state
Referenced by StandaloneAudioProcessorPlayer::preProcessBlock().
The documentation for this class was generated from the following file:
gin_sampleplayer.h