Gin: PluginWrapper Class Reference
PluginWrapper Class Reference
gin_standaloneplugin » standaloneplugin
#include <gin_pluginwrapper.h>
Public Member Functions
PluginWrapper (std::unique_ptr< juce::AudioProcessor > p)
void prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock) override
void processBlock (juce::AudioBuffer< float > &buffer, juce::MidiBuffer &midiMessages) override
Public Member Functions inherited from AudioProcessorWrapper
AudioProcessorWrapper (std::unique_ptr< juce::AudioProcessor > p)
~AudioProcessorWrapper () override
const juce::String getName () const override
juce::StringArray getAlternateDisplayNames () const override
void setRateAndBufferSizeDetails (double newSampleRate, int newBlockSize) noexcept
void prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock) override
void releaseResources () override
void memoryWarningReceived () override
void processBlock (juce::AudioBuffer< float > &buffer, juce::MidiBuffer &midiMessages) override
void processBlock (juce::AudioBuffer< double > &buffer, juce::MidiBuffer &midiMessages) override
void processBlockBypassed (juce::AudioBuffer< float > &buffer, juce::MidiBuffer &midiMessages) override
void processBlockBypassed (juce::AudioBuffer< double > &buffer, juce::MidiBuffer &midiMessages) override
bool canAddBus (bool isInput) const override
bool canRemoveBus (bool isInput) const override
bool supportsDoublePrecisionProcessing () const override
double getTailLengthSeconds () const override
bool acceptsMidi () const override
bool producesMidi () const override
bool supportsMPE () const override
bool isMidiEffect () const override
void reset () override
juce::AudioProcessorParameter * getBypassParameter () const override
void setNonRealtime (bool isNonRealtime) noexcept override
juce::AudioProcessorEditor * createEditor () override
bool hasEditor () const override
void refreshParameterList () override
int getNumPrograms () override
int getCurrentProgram () override
void setCurrentProgram (int index) override
const juce::String getProgramName (int index) override
void changeProgramName (int index, const juce::String &newName) override
void getStateInformation (juce::MemoryBlock &destData) override
void getCurrentProgramStateInformation (juce::MemoryBlock &destData) override
void setStateInformation (const void *data, int sizeInBytes) override
void setCurrentProgramStateInformation (const void *data, int sizeInBytes) override
void numChannelsChanged () override
void numBusesChanged () override
void processorLayoutsChanged () override
void addListener (juce::AudioProcessorListener *newListener) override
void removeListener (juce::AudioProcessorListener *listenerToRemove) override
void setPlayHead (juce::AudioPlayHead *newPlayHead) override
void audioWorkgroupContextChanged (const juce::AudioWorkgroup &workgroup) override
juce::VST2ClientExtensions * getVST2ClientExtensions () override
juce::VST3ClientExtensions * getVST3ClientExtensions () override
CurveData getResponseCurve (CurveData::Type curveType) const override
void updateTrackProperties (const TrackProperties &properties) override
Public Attributes
AudioFifo scopeFifo
Public Attributes inherited from AudioProcessorWrapper
std::unique_ptr< juce::AudioProcessor > proc
Constructor & Destructor Documentation
PluginWrapper()
PluginWrapper::PluginWrapper (std::unique_ptr< juce::AudioProcessor > p)
References scopeFifo, and AudioFifo::setSize().
Member Function Documentation
prepareToPlay()
void PluginWrapper::prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock) override
References AudioProcessorWrapper::prepareToPlay().
processBlock()
void PluginWrapper::processBlock (juce::AudioBuffer< float > & buffer, juce::MidiBuffer & midiMessages) override
References AudioFifo::getFreeSpace(), AudioFifo::getNumChannels(), AudioProcessorWrapper::processBlock(), scopeFifo, AudioFifo::setSize(), and AudioFifo::write().
Member Data Documentation
scopeFifo
AudioFifo PluginWrapper::scopeFifo
Referenced by PluginWrapper(), and processBlock().
The documentation for this class was generated from the following file:
gin_pluginwrapper.h