Gin: SingleLineTextEditor Class Reference
SingleLineTextEditor Class Reference
gin » components
An editable text box.
Inherits Component, TextInputTarget, and SettableTooltipClient.
Classes
class InputFilter
Base class for input filters that can be applied to a TextEditor to restrict the text that can be entered.
class LengthAndCharacterRestriction
An input filter for a TextEditor that limits the length of text and/or the characters that it may contain.
class Listener
Receives callbacks from a TextEditor component when it changes.
struct LookAndFeelMethods
This abstract base class is implemented by LookAndFeel classes to provide TextEditor drawing functionality.
Public Types
enum ColourIds {
backgroundColourId = 0x1000200, textColourId = 0x1000201, highlightColourId = 0x1000202, highlightedTextColourId = 0x1000203,
outlineColourId = 0x1000205, focusedOutlineColourId = 0x1000206, shadowColourId = 0x1000207
}
A set of colour IDs to use to change the colour of various aspects of the editor.
Public Member Functions
SingleLineTextEditor (const juce::String &componentName=juce::String())
Creates a new, empty text editor.
~SingleLineTextEditor () override
Destructor.
void setTabKeyUsedAsCharacter (bool shouldTabKeyBeUsed)
Indicates whether the tab key should be accepted and used to input a tab character, or whether it gets ignored.
bool isTabKeyUsedAsCharacter () const
Returns true if the tab key is being used for input.
void setEscapeAndReturnKeysConsumed (bool shouldBeConsumed) noexcept
This can be used to change whether escape and return keypress events are propagated up to the parent component.
void setReadOnly (bool shouldBeReadOnly)
Changes the editor to read-only mode.
bool isReadOnly () const noexcept
Returns true if the editor is in read-only mode.
void setCaretVisible (bool shouldBeVisible)
Makes the caret visible or invisible.
bool isCaretVisible () const noexcept
Returns true if the caret is enabled.
void setPopupMenuEnabled (bool menuEnabled)
Allows a right-click menu to appear for the editor.
bool isPopupMenuEnabled () const noexcept
Returns true if the right-click menu is enabled.
bool isPopupMenuCurrentlyActive () const noexcept
Returns true if a popup-menu is currently being displayed.
void setFont (const juce::Font &newFont)
Sets the font to use for newly added text.
void applyFontToAllText (const juce::Font &newFont)
Applies a font to all the text in the editor.
const juce::Font & getFont () const noexcept
Returns the font that's currently being used for new text.
void setJustificationType (juce::Justification just)
void setSelectAllWhenFocused (bool shouldSelectAll)
If set to true, focusing on the editor will highlight all its text.
void setTextToShowWhenEmpty (const juce::String &text, juce::Colour colourToUse)
When the text editor is empty, it can be set to display a message.
void addListener (SingleLineTextEditor::Listener *newListener)
Registers a listener to be told when things happen to the text.
void removeListener (SingleLineTextEditor::Listener *listenerToRemove)
Deregisters a listener.
juce::String getText () const
Returns the entire contents of the editor.
juce::String getTextInRange (const juce::Range< int > &textRange) const override
Returns a section of the contents of the editor.
bool isEmpty () const
Returns true if there are no characters in the editor.
void setText (const juce::String &newText, bool sendTextChangeMessage=true)
Sets the entire content of the editor.
juce::Value & getTextValue ()
Returns a Value object that can be used to get or set the text.
void insertTextAtCaret (const juce::String &textToInsert) override
Inserts some text at the current caret position.
void clear ()
Deletes all the text from the editor.
void cut ()
Deletes the currently selected region.
void copy ()
Copies the currently selected region to the clipboard.
void paste ()
Pastes the contents of the clipboard into the editor at the caret position.
int getCaretPosition () const
Returns the current index of the caret.
void setCaretPosition (int newIndex)
Moves the caret to be in front of a given character.
juce::Rectangle< int > getCaretRectangle () override
Get the graphical position of the caret.
void setHighlightedRegion (const juce::Range< int > &newSelection) override
Selects a section of the text.
juce::Range< int > getHighlightedRegion () const override
Returns the range of characters that are selected.
juce::String getHighlightedText () const
Returns the section of text that is currently selected.
int getTextIndexAt (int x, int y)
Finds the index of the character at a given position.
int getTotalNumChars () const
Counts the number of characters in the text.
int getTextWidth () const
Returns the total width of the text, as it is currently laid-out.
int getTextHeight () const
Returns the maximum height of the text, as it is currently laid-out.
void moveCaretToEnd ()
bool moveCaretLeft (bool moveInWholeWordSteps, bool selecting)
bool moveCaretRight (bool moveInWholeWordSteps, bool selecting)
bool moveCaretUp (bool selecting)
bool moveCaretDown (bool selecting)
bool pageUp (bool selecting)
bool pageDown (bool selecting)
bool scrollDown ()
bool scrollUp ()
bool moveCaretToTop (bool selecting)
bool moveCaretToStartOfLine (bool selecting)
bool moveCaretToEnd (bool selecting)
bool moveCaretToEndOfLine (bool selecting)
bool deleteBackwards (bool moveInWholeWordSteps)
bool deleteForwards (bool moveInWholeWordSteps)
bool copyToClipboard ()
bool cutToClipboard ()
bool pasteFromClipboard ()
bool selectAll ()
bool undo ()
bool redo ()
virtual void addPopupMenuItems (juce::PopupMenu &menuToAddTo, const juce::MouseEvent *mouseClickEvent)
This adds the items to the popup menu.
virtual void performPopupMenuAction (int menuItemID)
This is called to perform one of the items that was shown on the popup menu.
void setInputFilter (InputFilter *newFilter, bool takeOwnership)
Sets an input filter that should be applied to this editor.
InputFilter * getInputFilter () const noexcept
Returns the current InputFilter, as set by setInputFilter().
void setInputRestrictions (int maxTextLength, const juce::String &allowedCharacters=juce::String())
Sets limits on the characters that can be entered.
void setKeyboardType (VirtualKeyboardType type) noexcept
void paint (juce::Graphics &) override
void paintOverChildren (juce::Graphics &) override
void mouseDown (const juce::MouseEvent &) override
void mouseUp (const juce::MouseEvent &) override
void mouseDrag (const juce::MouseEvent &) override
void mouseDoubleClick (const juce::MouseEvent &) override
void mouseWheelMove (const juce::MouseEvent &, const juce::MouseWheelDetails &) override
bool keyPressed (const juce::KeyPress &) override
bool keyStateChanged (bool) override
void focusGained (FocusChangeType) override
void focusLost (FocusChangeType) override
void resized () override
void enablementChanged () override
void colourChanged () override
void lookAndFeelChanged () override
bool isTextInputActive () const override
void setTemporaryUnderlining (const juce::Array< juce::Range< int > > &) override
VirtualKeyboardType getKeyboardType () override
Protected Member Functions
void textChanged ()
Used internally to dispatch a text-change message.
void newTransaction ()
Begins a new transaction in the UndoManager.
virtual void returnPressed ()
Can be overridden to intercept return key presses directly.
virtual void escapePressed ()
Can be overridden to intercept escape key presses directly.
Detailed Description
An editable text box.
A TextEditor can either be in single- or multi-line mode, and supports mixed fonts and colours.
This is a hacked up version of the JUCE TextEditor that supports all justification modes
See also
TextEditor::Listener, Label
Member Enumeration Documentation
ColourIds
enum SingleLineTextEditor::ColourIds
A set of colour IDs to use to change the colour of various aspects of the editor.
These constants can be used either via the Component::setColour(), or LookAndFeel::setColour() methods.
NB: You can also set the caret colour using CaretComponent::caretColourId
See also
Component::setColour, Component::findColour, LookAndFeel::setColour, LookAndFeel::findColour
Enumerator
backgroundColourId
The colour to use for the text component's background - this can be transparent if necessary.
textColourId
The colour that will be used when text is added to the editor.
Note that because the editor can contain multiple colours, calling this method won't change the colour of existing text - to do that, call applyFontToAllText() after calling this method.
highlightColourId
The colour with which to fill the background of highlighted sections of the text - this can be transparent if you don't want to show any highlighting.
highlightedTextColourId
The colour with which to draw the text in highlighted sections.
outlineColourId
If this is non-transparent, it will be used to draw a box around the edge of the component.
focusedOutlineColourId
If this is non-transparent, it will be used to draw a box around the edge of the component when it has focus.
shadowColourId
If this is non-transparent, it'll be used to draw an inner shadow around the edge of the editor.
Constructor & Destructor Documentation
SingleLineTextEditor()
SingleLineTextEditor::SingleLineTextEditor (const juce::String & componentName = juce::String()) explicit
Creates a new, empty text editor.
Parameters
componentName the name to pass to the component for it to use as its name
~SingleLineTextEditor()
SingleLineTextEditor::~SingleLineTextEditor () override
Destructor.
Member Function Documentation
setTabKeyUsedAsCharacter()
void SingleLineTextEditor::setTabKeyUsedAsCharacter (bool shouldTabKeyBeUsed)
Indicates whether the tab key should be accepted and used to input a tab character, or whether it gets ignored.
By default the tab key is ignored, so that it can be used to switch keyboard focus between components.
isTabKeyUsedAsCharacter()
bool SingleLineTextEditor::isTabKeyUsedAsCharacter () const
Returns true if the tab key is being used for input.
See also
setTabKeyUsedAsCharacter
References isReadOnly(), setCaretVisible(), setEscapeAndReturnKeysConsumed(), and setReadOnly().
setEscapeAndReturnKeysConsumed()
void SingleLineTextEditor::setEscapeAndReturnKeysConsumed (bool shouldBeConsumed) noexcept
This can be used to change whether escape and return keypress events are propagated up to the parent component.
The default here is true, meaning that these events are not allowed to reach the parent, but you may want to allow them through so that they can trigger other actions, e.g. closing a dialog box, etc.
Referenced by isTabKeyUsedAsCharacter().
setReadOnly()
void SingleLineTextEditor::setReadOnly (bool shouldBeReadOnly)
Changes the editor to read-only mode.
By default, the text editor is not read-only. If you're making it read-only, you might also want to call setCaretVisible (false) to get rid of the caret.
The text can still be highlighted and copied when in read-only mode.
See also
isReadOnly, setCaretVisible
Referenced by isTabKeyUsedAsCharacter().
isReadOnly()
bool SingleLineTextEditor::isReadOnly () const noexcept
Returns true if the editor is in read-only mode.
Referenced by isCaretVisible(), and isTabKeyUsedAsCharacter().
setCaretVisible()
void SingleLineTextEditor::setCaretVisible (bool shouldBeVisible)
Makes the caret visible or invisible.
By default the caret is visible.
See also
setCaretColour, setCaretPosition
Referenced by isTabKeyUsedAsCharacter().
isCaretVisible()
bool SingleLineTextEditor::isCaretVisible () const noexcept
Returns true if the caret is enabled.
See also
setCaretVisible
References isReadOnly(), and setPopupMenuEnabled().
setPopupMenuEnabled()
void SingleLineTextEditor::setPopupMenuEnabled (bool menuEnabled)
Allows a right-click menu to appear for the editor.
(This defaults to being enabled).
If enabled, right-clicking (or command-clicking on the Mac) will pop up a menu of options such as cut/copy/paste, undo/redo, etc.
Referenced by isCaretVisible().
isPopupMenuEnabled()
bool SingleLineTextEditor::isPopupMenuEnabled () const noexcept
Returns true if the right-click menu is enabled.
See also
setPopupMenuEnabled
isPopupMenuCurrentlyActive()
bool SingleLineTextEditor::isPopupMenuCurrentlyActive () const noexcept
Returns true if a popup-menu is currently being displayed.
setFont()
void SingleLineTextEditor::setFont (const juce::Font & newFont)
Sets the font to use for newly added text.
This will change the font that will be used next time any text is added or entered into the editor. It won't change the font of any existing text - to do that, use applyFontToAllText() instead.
See also
applyFontToAllText
applyFontToAllText()
void SingleLineTextEditor::applyFontToAllText (const juce::Font & newFont)
Applies a font to all the text in the editor.
This will also set the current font to use for any new text that's added.
See also
setFont
getFont()
const juce::Font& SingleLineTextEditor::getFont () const noexcept
Returns the font that's currently being used for new text.
See also
setFont
setJustificationType()
void SingleLineTextEditor::setJustificationType (juce::Justification just)
References setSelectAllWhenFocused(), and setTextToShowWhenEmpty().
setSelectAllWhenFocused()
void SingleLineTextEditor::setSelectAllWhenFocused (bool shouldSelectAll)
If set to true, focusing on the editor will highlight all its text.
(Set to false by default).
This is useful for boxes where you expect the user to re-enter all the text when they focus on the component, rather than editing what's already there.
Referenced by setJustificationType().
setTextToShowWhenEmpty()
void SingleLineTextEditor::setTextToShowWhenEmpty (const juce::String & text, juce::Colour colourToUse)
When the text editor is empty, it can be set to display a message.
This is handy for things like telling the user what to type in the box - the string is only displayed, it's not taken to actually be the contents of the editor.
Referenced by setJustificationType().
addListener()
void SingleLineTextEditor::addListener (SingleLineTextEditor::Listener * newListener)
Registers a listener to be told when things happen to the text.
See also
removeListener
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
removeListener()
void SingleLineTextEditor::removeListener (SingleLineTextEditor::Listener * listenerToRemove)
Deregisters a listener.
See also
addListener
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
getText()
juce::String SingleLineTextEditor::getText () const
Returns the entire contents of the editor.
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
getTextInRange()
juce::String SingleLineTextEditor::getTextInRange (const juce::Range< int > & textRange) const override
Returns a section of the contents of the editor.
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
isEmpty()
bool SingleLineTextEditor::isEmpty () const
Returns true if there are no characters in the editor.
This is far more efficient than calling getText().isEmpty().
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
setText()
void SingleLineTextEditor::setText (const juce::String & newText, bool sendTextChangeMessage = true)
Sets the entire content of the editor.
This will clear the editor and insert the given text (using the current text colour and font). You can set the current text colour using
setColour (TextEditor::textColourId, ...);
Parameters
newText the text to add
sendTextChangeMessage if true, this will cause a change message to be sent to all the listeners.
See also
insertTextAtCaret
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
getTextValue()
juce::Value& SingleLineTextEditor::getTextValue ()
Returns a Value object that can be used to get or set the text.
Bear in mind that this operate quite slowly if your text box contains large amounts of text, as it needs to dynamically build the string that's involved. It's best used for small text boxes.
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
insertTextAtCaret()
void SingleLineTextEditor::insertTextAtCaret (const juce::String & textToInsert) override
Inserts some text at the current caret position.
If a section of the text is highlighted, it will be replaced by this string, otherwise it will be inserted.
To delete a section of text, you can use setHighlightedRegion() to highlight it, and call insertTextAtCaret (String()).
See also
setCaretPosition, getCaretPosition, setHighlightedRegion
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
clear()
void SingleLineTextEditor::clear ()
Deletes all the text from the editor.
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
cut()
void SingleLineTextEditor::cut ()
Deletes the currently selected region.
This doesn't copy the deleted section to the clipboard - if you need to do that, call copy() first.
See also
copy, paste, SystemClipboard
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
copy()
void SingleLineTextEditor::copy ()
Copies the currently selected region to the clipboard.
See also
cut, paste, SystemClipboard
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
paste()
void SingleLineTextEditor::paste ()
Pastes the contents of the clipboard into the editor at the caret position.
See also
cut, copy, SystemClipboard
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
getCaretPosition()
int SingleLineTextEditor::getCaretPosition () const
Returns the current index of the caret.
See also
setCaretPosition
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
setCaretPosition()
void SingleLineTextEditor::setCaretPosition (int newIndex)
Moves the caret to be in front of a given character.
See also
getCaretPosition, moveCaretToEnd
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
getCaretRectangle()
juce::Rectangle<int> SingleLineTextEditor::getCaretRectangle () override
Get the graphical position of the caret.
The rectangle returned is relative to the component's top-left corner.
See also
scrollEditorToPositionCaret
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
setHighlightedRegion()
void SingleLineTextEditor::setHighlightedRegion (const juce::Range< int > & newSelection) override
Selects a section of the text.
Referenced by SingleLineTextEditor::Listener::sltextEditorFocusLost().
getHighlightedRegion()
juce::Range<int> SingleLineTextEditor::getHighlightedRegion () const override
Returns the range of characters that are selected.
If nothing is selected, this will return an empty range.
See also
setHighlightedRegion
References getHighlightedText(), getTextHeight(), getTextIndexAt(), getTextWidth(), getTotalNumChars(), moveCaretDown(), moveCaretLeft(), moveCaretRight(), moveCaretToEnd(), moveCaretUp(), pageDown(), and pageUp().
getHighlightedText()
juce::String SingleLineTextEditor::getHighlightedText () const
Returns the section of text that is currently selected.
Referenced by getHighlightedRegion().
getTextIndexAt()
int SingleLineTextEditor::getTextIndexAt (int x, int y)
Finds the index of the character at a given position.
The coordinates are relative to the component's top-left.
Referenced by getHighlightedRegion().
getTotalNumChars()
int SingleLineTextEditor::getTotalNumChars () const
Counts the number of characters in the text.
This is quicker than getting the text as a string if you just need to know the length.
Referenced by getHighlightedRegion().
getTextWidth()
int SingleLineTextEditor::getTextWidth () const
Returns the total width of the text, as it is currently laid-out.
This may be larger than the size of the TextEditor, and can change when the TextEditor is resized or the text changes.
Referenced by getHighlightedRegion().
getTextHeight()
int SingleLineTextEditor::getTextHeight () const
Returns the maximum height of the text, as it is currently laid-out.
This may be larger than the size of the TextEditor, and can change when the TextEditor is resized or the text changes.
Referenced by getHighlightedRegion().
moveCaretToEnd() [1/2]
void SingleLineTextEditor::moveCaretToEnd ()
Referenced by getHighlightedRegion(), and scrollUp().
moveCaretLeft()
bool SingleLineTextEditor::moveCaretLeft (bool moveInWholeWordSteps, bool selecting)
Referenced by getHighlightedRegion().
moveCaretRight()
bool SingleLineTextEditor::moveCaretRight (bool moveInWholeWordSteps, bool selecting)
Referenced by getHighlightedRegion().
moveCaretUp()
bool SingleLineTextEditor::moveCaretUp (bool selecting)
Referenced by getHighlightedRegion().
moveCaretDown()
bool SingleLineTextEditor::moveCaretDown (bool selecting)
Referenced by getHighlightedRegion().
pageUp()
bool SingleLineTextEditor::pageUp (bool selecting)
Referenced by getHighlightedRegion().
pageDown()
bool SingleLineTextEditor::pageDown (bool selecting)
Referenced by getHighlightedRegion().
scrollDown()
bool SingleLineTextEditor::scrollDown ()
scrollUp()
bool SingleLineTextEditor::scrollUp ()
References addPopupMenuItems(), copyToClipboard(), cutToClipboard(), deleteBackwards(), deleteForwards(), moveCaretToEnd(), moveCaretToEndOfLine(), moveCaretToStartOfLine(), moveCaretToTop(), pasteFromClipboard(), performPopupMenuAction(), redo(), selectAll(), and undo().
moveCaretToTop()
bool SingleLineTextEditor::moveCaretToTop (bool selecting)
Referenced by scrollUp().
moveCaretToStartOfLine()
bool SingleLineTextEditor::moveCaretToStartOfLine (bool selecting)
Referenced by scrollUp().
moveCaretToEnd() [2/2]
bool SingleLineTextEditor::moveCaretToEnd (bool selecting)
moveCaretToEndOfLine()
bool SingleLineTextEditor::moveCaretToEndOfLine (bool selecting)
Referenced by scrollUp().
deleteBackwards()
bool SingleLineTextEditor::deleteBackwards (bool moveInWholeWordSteps)
Referenced by scrollUp().
deleteForwards()
bool SingleLineTextEditor::deleteForwards (bool moveInWholeWordSteps)
Referenced by scrollUp().
copyToClipboard()
bool SingleLineTextEditor::copyToClipboard ()
Referenced by scrollUp().
cutToClipboard()
bool SingleLineTextEditor::cutToClipboard ()
Referenced by scrollUp().
pasteFromClipboard()
bool SingleLineTextEditor::pasteFromClipboard ()
Referenced by scrollUp().
selectAll()
bool SingleLineTextEditor::selectAll ()
Referenced by scrollUp().
undo()
bool SingleLineTextEditor::undo ()
Referenced by scrollUp().
redo()
bool SingleLineTextEditor::redo ()
Referenced by scrollUp().
addPopupMenuItems()
virtual void SingleLineTextEditor::addPopupMenuItems (juce::PopupMenu & menuToAddTo, const juce::MouseEvent * mouseClickEvent) virtual
This adds the items to the popup menu.
By default it adds the cut/copy/paste items, but you can override this if you need to replace these with your own items.
If you want to add your own items to the existing ones, you can override this, call the base class's addPopupMenuItems() method, then append your own items.
When the menu has been shown, performPopupMenuAction() will be called to perform the item that the user has chosen.
The default menu items will be added using item IDs from the StandardApplicationCommandIDs namespace.
If this was triggered by a mouse-click, the mouseClickEvent parameter will be a pointer to the info about it, or may be null if the menu is being triggered by some other means.
See also
performPopupMenuAction, setPopupMenuEnabled, isPopupMenuEnabled
Referenced by scrollUp().
performPopupMenuAction()
virtual void SingleLineTextEditor::performPopupMenuAction (int menuItemID) virtual
This is called to perform one of the items that was shown on the popup menu.
If you've overridden addPopupMenuItems(), you should also override this to perform the actions that you've added.
If you've overridden addPopupMenuItems() but have still left the default items on the menu, remember to call the superclass's performPopupMenuAction() so that it can perform the default actions if that's what the user clicked on.
See also
addPopupMenuItems, setPopupMenuEnabled, isPopupMenuEnabled
Referenced by scrollUp().
setInputFilter()
void SingleLineTextEditor::setInputFilter (InputFilter * newFilter, bool takeOwnership)
Sets an input filter that should be applied to this editor.
The filter can be nullptr, to remove any existing filters. If takeOwnership is true, then the filter will be owned and deleted by the editor when no longer needed.
getInputFilter()
InputFilter* SingleLineTextEditor::getInputFilter () const noexcept
Returns the current InputFilter, as set by setInputFilter().
References setInputRestrictions().
setInputRestrictions()
void SingleLineTextEditor::setInputRestrictions (int maxTextLength, const juce::String & allowedCharacters = juce::String())
Sets limits on the characters that can be entered.
This is just a shortcut that passes an instance of the LengthAndCharacterRestriction class to setInputFilter().
Parameters
maxTextLength if this is > 0, it sets a maximum length limit; if 0, no limit is set
allowedCharacters if this is non-empty, then only characters that occur in this string are allowed to be entered into the editor.
Referenced by getInputFilter().
setKeyboardType()
void SingleLineTextEditor::setKeyboardType (VirtualKeyboardType type) noexcept
paint()
void SingleLineTextEditor::paint (juce::Graphics &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
paintOverChildren()
void SingleLineTextEditor::paintOverChildren (juce::Graphics &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
mouseDown()
void SingleLineTextEditor::mouseDown (const juce::MouseEvent &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
mouseUp()
void SingleLineTextEditor::mouseUp (const juce::MouseEvent &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
mouseDrag()
void SingleLineTextEditor::mouseDrag (const juce::MouseEvent &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
mouseDoubleClick()
void SingleLineTextEditor::mouseDoubleClick (const juce::MouseEvent &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
mouseWheelMove()
void SingleLineTextEditor::mouseWheelMove (const juce::MouseEvent & , const juce::MouseWheelDetails &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
keyPressed()
bool SingleLineTextEditor::keyPressed (const juce::KeyPress &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
keyStateChanged()
bool SingleLineTextEditor::keyStateChanged (bool) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
focusGained()
void SingleLineTextEditor::focusGained (FocusChangeType) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
focusLost()
void SingleLineTextEditor::focusLost (FocusChangeType) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
resized()
void SingleLineTextEditor::resized () override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
enablementChanged()
void SingleLineTextEditor::enablementChanged () override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
colourChanged()
void SingleLineTextEditor::colourChanged () override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
lookAndFeelChanged()
void SingleLineTextEditor::lookAndFeelChanged () override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
isTextInputActive()
bool SingleLineTextEditor::isTextInputActive () const override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
setTemporaryUnderlining()
void SingleLineTextEditor::setTemporaryUnderlining (const juce::Array< juce::Range< int > > &) override
Referenced by SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods().
getKeyboardType()
VirtualKeyboardType SingleLineTextEditor::getKeyboardType () override
References escapePressed(), InsertAction, newTransaction(), returnPressed(), textChanged(), and TextHolderComponent.
textChanged()
void SingleLineTextEditor::textChanged () protected
Used internally to dispatch a text-change message.
Referenced by getKeyboardType().
newTransaction()
void SingleLineTextEditor::newTransaction () protected
Begins a new transaction in the UndoManager.
Referenced by getKeyboardType().
returnPressed()
virtual void SingleLineTextEditor::returnPressed () protected virtual
Can be overridden to intercept return key presses directly.
Referenced by getKeyboardType().
escapePressed()
virtual void SingleLineTextEditor::escapePressed () protected virtual
Can be overridden to intercept escape key presses directly.
Referenced by getKeyboardType().
The documentation for this class was generated from the following file:
gin_singlelinetexteditor.h