Gin: LRUCache< Key, Value, MaxSize > Class Template Reference
LRUCache< Key, Value, MaxSize > Class Template Reference
gin » utilities
A simple LRU (Least Recently Used) cache with a fixed maximum size.
#include <gin_lrucache.h>
Public Member Functions
LRUCache ()=default
Creates an empty LRU cache.
Value * get (const Key &key)
Returns a pointer to the cached value for the given key, or nullptr if not found.
const Value * get (const Key &key) const
Returns a const pointer to the cached value for the given key, or nullptr if not found.
void put (const Key &key, Value value)
Inserts or updates a value in the cache.
template<typename Factory >
Value & getOrCreate (const Key &key, Factory &&factory)
Gets an existing value or creates a new one using the provided factory function.
bool remove (const Key &key)
Removes an item from the cache.
bool contains (const Key &key) const
Checks if a key exists in the cache.
size_t size () const noexcept
Returns the number of items currently in the cache.
bool empty () const noexcept
Checks if the cache is empty.
void clear ()
Removes all items from the cache.
Static Public Member Functions
static constexpr size_t maxSize () noexcept
Returns the maximum number of items the cache can hold.
Detailed Description
template<typename Key, typename Value, size_t MaxSize>
class LRUCache< Key, Value, MaxSize >
A simple LRU (Least Recently Used) cache with a fixed maximum size.
This template class provides a cache that automatically evicts the least recently accessed items when it reaches capacity. It uses a hash map for O(1) average-case lookups and a linked list to track access order.
The cache is not thread-safe. If you need thread safety, you should synchronize access externally.
Example usage:
LRUCache<juce::String, int, 10> cache;
// Insert items
cache.put ("one", 1);
cache.put ("two", 2);
// Retrieve items
if (auto* value = cache.get ("one"))
    process (*value);
// Use getOrCreate for lazy initialization
auto& value = cache.getOrCreate ("three", [] { return expensiveComputation(); });
Template Parameters
Key The type used as the cache key. Must be hashable via std::hash.
Value The type of values stored in the cache.
MaxSize The maximum number of items the cache can hold.
Constructor & Destructor Documentation
LRUCache()
template<typename Key , typename Value , size_t MaxSize> LRUCache< Key, Value, MaxSize >::LRUCache () default
Creates an empty LRU cache.
Member Function Documentation
get() [1/2]
template<typename Key , typename Value , size_t MaxSize> Value * LRUCache< Key, Value, MaxSize >::get (const Key & key)
Returns a pointer to the cached value for the given key, or nullptr if not found.
Accessing an item moves it to the front of the cache (most recently used).
Parameters
key The key to look up
Returns
A pointer to the value if found, nullptr otherwise
Referenced by LRUCache< Key, Value, MaxSize >::get(), and LRUCache< Key, Value, MaxSize >::getOrCreate().
get() [2/2]
template<typename Key , typename Value , size_t MaxSize> const Value * LRUCache< Key, Value, MaxSize >::get (const Key & key) const
Returns a const pointer to the cached value for the given key, or nullptr if not found.
Accessing an item moves it to the front of the cache (most recently used).
Parameters
key The key to look up
Returns
A const pointer to the value if found, nullptr otherwise
References LRUCache< Key, Value, MaxSize >::get().
put()
template<typename Key , typename Value , size_t MaxSize> void LRUCache< Key, Value, MaxSize >::put (const Key & key, Value value)
Inserts or updates a value in the cache.
If the key already exists, its value is updated and it's moved to the front. If the cache is at capacity, the least recently used item is evicted.
Parameters
key The key to insert or update
value The value to store
Referenced by LRUCache< Key, Value, MaxSize >::getOrCreate().
getOrCreate()
template<typename Key , typename Value , size_t MaxSize> template<typename Factory > Value & LRUCache< Key, Value, MaxSize >::getOrCreate (const Key & key, Factory && factory)
Gets an existing value or creates a new one using the provided factory function.
If the key exists, returns a reference to its value (moving it to front). If the key doesn't exist, calls the factory function to create a value, inserts it, and returns a reference to it.
Parameters
key The key to look up or create
factory A callable that takes no arguments and returns a Value
Returns
A reference to the cached value
References LRUCache< Key, Value, MaxSize >::get(), and LRUCache< Key, Value, MaxSize >::put().
remove()
template<typename Key , typename Value , size_t MaxSize> bool LRUCache< Key, Value, MaxSize >::remove (const Key & key)
Removes an item from the cache.
Parameters
key The key to remove
Returns
true if the item was found and removed, false otherwise
contains()
template<typename Key , typename Value , size_t MaxSize> bool LRUCache< Key, Value, MaxSize >::contains (const Key & key) const
Checks if a key exists in the cache.
Note: This does NOT update the access order.
Parameters
key The key to check
Returns
true if the key exists, false otherwise
size()
template<typename Key , typename Value , size_t MaxSize> size_t LRUCache< Key, Value, MaxSize >::size () const noexcept
Returns the number of items currently in the cache.
Returns
The current size of the cache
empty()
template<typename Key , typename Value , size_t MaxSize> bool LRUCache< Key, Value, MaxSize >::empty () const noexcept
Checks if the cache is empty.
Returns
true if the cache contains no items
clear()
template<typename Key , typename Value , size_t MaxSize> void LRUCache< Key, Value, MaxSize >::clear ()
Removes all items from the cache.
maxSize()
template<typename Key , typename Value , size_t MaxSize> static constexpr size_t LRUCache< Key, Value, MaxSize >::maxSize () static constexpr noexcept
Returns the maximum number of items the cache can hold.
Returns
The maximum capacity
The documentation for this class was generated from the following file:
gin_lrucache.h