Gin: EasedValueSmoother< T, EasingFunction > Class Template Reference
EasedValueSmoother< T, EasingFunction > Class Template Reference
gin_dsp » dsp
Smooths a value using an easing function for natural-feeling transitions.
#include <gin_easedvaluesmoother.h>
Public Member Functions
void setSampleRate (double sr)
void setTime (double t)
bool isSmoothing ()
void reset ()
T getCurrentValue ()
T * getValuePtr ()
void snapToValue ()
void process (int n)
void setValue (T v)
void updateValue ()
T getNextValue ()
void setValueUnsmoothed (T v)
Detailed Description
template<class T, class EasingFunction = QuadraticInOutEasing>
class EasedValueSmoother< T, EasingFunction >
Smooths a value using an easing function for natural-feeling transitions.
EasedValueSmoother provides smooth parameter transitions using easing curves instead of linear interpolation. This creates more natural, aesthetically pleasing animations and parameter changes.
The easing function is specified as a template parameter, allowing for compile-time selection of the curve shape. Any of the easing function objects defined in this file can be used.
Template Parameters
T The numeric type for values (typically float or double)
EasingFunction Function object providing the easing curve (defaults to QuadraticInOutEasing)
Example:
// Default quadratic in/out easing
EasedValueSmoother<float> smoother1;
// Elastic easing for bouncy effect
EasedValueSmoother<float, ElasticOutEasing> smoother2;
// Exponential easing for sharp transitions
EasedValueSmoother<float, ExponentialInOutEasing> smoother3;
Member Function Documentation
setSampleRate()
template<class T , class EasingFunction = QuadraticInOutEasing> void EasedValueSmoother< T, EasingFunction >::setSampleRate (double sr)
References EasedValueSmoother< T, EasingFunction >::reset().
setTime()
template<class T , class EasingFunction = QuadraticInOutEasing> void EasedValueSmoother< T, EasingFunction >::setTime (double t)
References EasedValueSmoother< T, EasingFunction >::reset().
isSmoothing()
template<class T , class EasingFunction = QuadraticInOutEasing> bool EasedValueSmoother< T, EasingFunction >::isSmoothing ()
reset()
template<class T , class EasingFunction = QuadraticInOutEasing> void EasedValueSmoother< T, EasingFunction >::reset ()
Referenced by EasedValueSmoother< T, EasingFunction >::setSampleRate(), and EasedValueSmoother< T, EasingFunction >::setTime().
getCurrentValue()
template<class T , class EasingFunction = QuadraticInOutEasing> T EasedValueSmoother< T, EasingFunction >::getCurrentValue ()
getValuePtr()
template<class T , class EasingFunction = QuadraticInOutEasing> T * EasedValueSmoother< T, EasingFunction >::getValuePtr ()
snapToValue()
template<class T , class EasingFunction = QuadraticInOutEasing> void EasedValueSmoother< T, EasingFunction >::snapToValue ()
process()
template<class T , class EasingFunction = QuadraticInOutEasing> void EasedValueSmoother< T, EasingFunction >::process (int n)
References EasedValueSmoother< T, EasingFunction >::updateValue().
setValue()
template<class T , class EasingFunction = QuadraticInOutEasing> void EasedValueSmoother< T, EasingFunction >::setValue (T v)
updateValue()
template<class T , class EasingFunction = QuadraticInOutEasing> void EasedValueSmoother< T, EasingFunction >::updateValue ()
Referenced by EasedValueSmoother< T, EasingFunction >::getNextValue(), and EasedValueSmoother< T, EasingFunction >::process().
getNextValue()
template<class T , class EasingFunction = QuadraticInOutEasing> T EasedValueSmoother< T, EasingFunction >::getNextValue ()
References EasedValueSmoother< T, EasingFunction >::updateValue().
setValueUnsmoothed()
template<class T , class EasingFunction = QuadraticInOutEasing> void EasedValueSmoother< T, EasingFunction >::setValueUnsmoothed (T v)
The documentation for this class was generated from the following file:
gin_easedvaluesmoother.h