Gin: ProcessorEditorBase Class Reference
ProcessorEditorBase Class Reference
gin_plugin » components
Base for plugin editor.
#include <gin_plugineditor.h>
Public Member Functions
ProcessorEditorBase (Processor &p, int cx_, int cy_)
~ProcessorEditorBase () override
void makeResizable (int minX, int minY, int maxX, int maxY)
void resized () override
void globalFocusChanged (juce::Component *) override
void paintOverChildren (juce::Graphics &g) override
void addControl (ParamComponent *c, int x=0, int y=0, int w=1, int h=1)
virtual juce::Rectangle< int > getControlsArea ()
virtual juce::Rectangle< int > getGridArea (int x, int y, int w=1, int h=1)
juce::Rectangle< int > getFullGridArea ()
int getGridWidth ()
int getGridHeight ()
virtual bool getUseIncreasedKeyboardAccessibility ()
virtual void setUseIncreasedKeyboardAccessibility (bool accessible)
Public Attributes
juce::ComponentBoundsConstrainer resizeLimits
Protected Member Functions
void setGridSize (int x, int y, int extraWidthPx=0, int extraHeightPx=0)
ParamComponent * componentForId (const juce::String &uid)
ParamComponent * componentForParam (Parameter &param)
Protected Attributes
Processor & ginProcessor
std::unique_ptr< juce::ResizableCornerComponent > resizer
const int cx
const int cy
juce::OwnedArray< ParamComponent > controls
int headerHeight = 40
int inset = 4
int cols = 0
int rows = 0
int extraWidthPx = 0
int extraHeightPx = 0
juce::TooltipWindow tooltipWindow { this, 0 }
Detailed Description
Base for plugin editor.
Constructor & Destructor Documentation
ProcessorEditorBase()
ProcessorEditorBase::ProcessorEditorBase (Processor & p, int cx_, int cy_)
~ProcessorEditorBase()
ProcessorEditorBase::~ProcessorEditorBase () override
Member Function Documentation
makeResizable()
void ProcessorEditorBase::makeResizable (int minX, int minY, int maxX, int maxY)
References addAndMakeVisible(), ginProcessor, resized(), resizeLimits, resizer, and Processor::state.
resized()
void ProcessorEditorBase::resized () override
References ginProcessor, resizer, and Processor::state.
Referenced by makeResizable().
globalFocusChanged()
void ProcessorEditorBase::globalFocusChanged (juce::Component *) override
References getUseIncreasedKeyboardAccessibility().
paintOverChildren()
void ProcessorEditorBase::paintOverChildren (juce::Graphics & g) override
References GinLookAndFeel::accentColourId, and getUseIncreasedKeyboardAccessibility().
addControl()
void ProcessorEditorBase::addControl (ParamComponent * c, int x = 0, int y = 0, int w = 1, int h = 1)
References addAndMakeVisible(), controls, and getGridArea().
getControlsArea()
virtual juce::Rectangle< int > ProcessorEditorBase::getControlsArea () virtual
getGridArea()
virtual juce::Rectangle< int > ProcessorEditorBase::getGridArea (int x, int y, int w = 1, int h = 1) virtual
Referenced by addControl().
getFullGridArea()
juce::Rectangle< int > ProcessorEditorBase::getFullGridArea ()
getGridWidth()
int ProcessorEditorBase::getGridWidth ()
References cx.
Referenced by PagedControlBox::addPage(), and ControlBox::getGridArea().
getGridHeight()
int ProcessorEditorBase::getGridHeight ()
References cy.
Referenced by PagedControlBox::addPage(), and ControlBox::getGridArea().
getUseIncreasedKeyboardAccessibility()
virtual bool ProcessorEditorBase::getUseIncreasedKeyboardAccessibility () virtual
Referenced by globalFocusChanged(), and paintOverChildren().
setUseIncreasedKeyboardAccessibility()
virtual void ProcessorEditorBase::setUseIncreasedKeyboardAccessibility (bool accessible) virtual
setGridSize()
void ProcessorEditorBase::setGridSize (int x, int y, int extraWidthPx = 0, int extraHeightPx = 0) protected
componentForId()
ParamComponent * ProcessorEditorBase::componentForId (const juce::String & uid) protected
componentForParam()
ParamComponent * ProcessorEditorBase::componentForParam (Parameter & param) protected
Member Data Documentation
resizeLimits
juce::ComponentBoundsConstrainer ProcessorEditorBase::resizeLimits
Referenced by makeResizable().
ginProcessor
Processor& ProcessorEditorBase::ginProcessor protected
Referenced by makeResizable(), and resized().
resizer
std::unique_ptr<juce::ResizableCornerComponent> ProcessorEditorBase::resizer protected
Referenced by makeResizable(), and resized().
cx
const int ProcessorEditorBase::cx protected
Referenced by getGridWidth().
cy
const int ProcessorEditorBase::cy protected
Referenced by getGridHeight().
controls
juce::OwnedArray<ParamComponent> ProcessorEditorBase::controls protected
Referenced by addControl().
headerHeight
int ProcessorEditorBase::headerHeight = 40 protected
inset
int ProcessorEditorBase::inset = 4 protected
cols
int ProcessorEditorBase::cols = 0 protected
rows
int ProcessorEditorBase::rows = 0 protected
extraWidthPx
int ProcessorEditorBase::extraWidthPx = 0 protected
extraHeightPx
int ProcessorEditorBase::extraHeightPx = 0 protected
tooltipWindow
juce::TooltipWindow ProcessorEditorBase::tooltipWindow { this, 0 } protected
The documentation for this class was generated from the following file:
gin_plugineditor.h