Gin: AudioSamplerBufferComponent Class Reference
AudioSamplerBufferComponent Class Reference
gin_dsp » components
Draws an AudioSampleBuffer thumbnail.
#include <gin_audiosamplerbuffercomponent.h>
Classes
class ScopedViewState
Public Member Functions
AudioSamplerBufferComponent ()
~AudioSamplerBufferComponent () override
void setBuffer (const juce::AudioSampleBuffer &)
const juce::AudioBuffer< float > & getBuffer ()
void clear ()
void setScrollable (bool s)
int getLength ()
void setHiResDisabled (bool b)
float getViewLeft ()
float getViewRight ()
void scrollViewBounds (float delta)
void setViewLeft (float left)
void setViewRight (float right)
void setViewBounds (float left, float right)
void setMaxZoom (float maxZoom)
void zoom (float centrePoint, float factor)
void setPlayheads (const std::vector< int > &playheads)
float xToSample (float x)
float sampleToX (float sample)
int lengthInSamples ()
void setLineColour (juce::Colour c)
void setBackgroundColour (juce::Colour c)
void paint (juce::Graphics &) override
void resized () override
void mouseWheelMove (const juce::MouseEvent &e, const juce::MouseWheelDetails &wheel) override
juce::MouseCursor getMouseCursor () override
void mouseDown (const juce::MouseEvent &e) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &e) override
Protected Member Functions
void paintBackground (juce::Graphics &g)
void paintPlayheads (juce::Graphics &g)
void paintChannelData (juce::Graphics &g, int channel, const juce::Rectangle< float > &r)
Detailed Description
Draws an AudioSampleBuffer thumbnail.
Constructor & Destructor Documentation
AudioSamplerBufferComponent()
AudioSamplerBufferComponent::AudioSamplerBufferComponent ()
~AudioSamplerBufferComponent()
AudioSamplerBufferComponent::~AudioSamplerBufferComponent () override
Member Function Documentation
setBuffer()
void AudioSamplerBufferComponent::setBuffer (const juce::AudioSampleBuffer &)
Referenced by SampleFileComponent::filesDropped(), and RetrospectiveBufferComponent::timerCallback().
getBuffer()
const juce::AudioBuffer< float > & AudioSamplerBufferComponent::getBuffer ()
clear()
void AudioSamplerBufferComponent::clear ()
setScrollable()
void AudioSamplerBufferComponent::setScrollable (bool s)
getLength()
int AudioSamplerBufferComponent::getLength ()
setHiResDisabled()
void AudioSamplerBufferComponent::setHiResDisabled (bool b)
getViewLeft()
float AudioSamplerBufferComponent::getViewLeft ()
getViewRight()
float AudioSamplerBufferComponent::getViewRight ()
scrollViewBounds()
void AudioSamplerBufferComponent::scrollViewBounds (float delta)
setViewLeft()
void AudioSamplerBufferComponent::setViewLeft (float left)
setViewRight()
void AudioSamplerBufferComponent::setViewRight (float right)
setViewBounds()
void AudioSamplerBufferComponent::setViewBounds (float left, float right)
setMaxZoom()
void AudioSamplerBufferComponent::setMaxZoom (float maxZoom)
zoom()
void AudioSamplerBufferComponent::zoom (float centrePoint, float factor)
setPlayheads()
void AudioSamplerBufferComponent::setPlayheads (const std::vector< int > & playheads)
Referenced by SampleFileComponent::timerCallback().
xToSample()
float AudioSamplerBufferComponent::xToSample (float x)
sampleToX()
float AudioSamplerBufferComponent::sampleToX (float sample)
lengthInSamples()
int AudioSamplerBufferComponent::lengthInSamples ()
setLineColour()
void AudioSamplerBufferComponent::setLineColour (juce::Colour c)
setBackgroundColour()
void AudioSamplerBufferComponent::setBackgroundColour (juce::Colour c)
paint()
void AudioSamplerBufferComponent::paint (juce::Graphics &) override
Referenced by SampleFileComponent::paint(), and RetrospectiveBufferComponent::paint().
resized()
void AudioSamplerBufferComponent::resized () override
mouseWheelMove()
void AudioSamplerBufferComponent::mouseWheelMove (const juce::MouseEvent & e, const juce::MouseWheelDetails & wheel) override
getMouseCursor()
juce::MouseCursor AudioSamplerBufferComponent::getMouseCursor () override
mouseDown()
void AudioSamplerBufferComponent::mouseDown (const juce::MouseEvent & e) override
mouseDrag()
void AudioSamplerBufferComponent::mouseDrag (const juce::MouseEvent & e) override
mouseUp()
void AudioSamplerBufferComponent::mouseUp (const juce::MouseEvent & e) override
paintBackground()
void AudioSamplerBufferComponent::paintBackground (juce::Graphics & g) protected
paintPlayheads()
void AudioSamplerBufferComponent::paintPlayheads (juce::Graphics & g) protected
paintChannelData()
void AudioSamplerBufferComponent::paintChannelData (juce::Graphics & g, int channel, const juce::Rectangle< float > & r) protected
The documentation for this class was generated from the following file:
gin_audiosamplerbuffercomponent.h