Gin: Wavetable Class Reference
Wavetable Class Reference
gin_dsp » dsp
Wrapper around juce::OwnedArray<BandLimitedLookupTable> for managing multiple wavetables.
#include <gin_wavetable.h>
Public Member Functions
Wavetable ()=default
Wavetable (Wavetable &&other) noexcept
Move constructor.
Wavetable & operator= (Wavetable &&other) noexcept
Move assignment operator.
void addTable (BandLimitedLookupTable *table)
Add a new BandLimitedLookupTable to the collection.
int getNumTables () const
Get the number of tables.
BandLimitedLookupTable * getTable (int index)
Get a table by index.
const BandLimitedLookupTable * getTable (int index) const
Get a table by index (const version)
BandLimitedLookupTable * operator[] (int index)
Array subscript operator for compatibility with OwnedArray usage.
const BandLimitedLookupTable * operator[] (int index) const
Array subscript operator for compatibility with OwnedArray usage (const version)
BandLimitedLookupTable * getUnchecked (int index)
Get unchecked access to a table (for compatibility with OwnedArray)
const BandLimitedLookupTable * getUnchecked (int index) const
Get unchecked access to a table (for compatibility with OwnedArray, const version)
int size () const
Get the number of tables (for compatibility with OwnedArray::size())
void clear ()
Clear all tables.
float process (int tableIndex, float note, float phase)
Process using a specific table index.
float processLinear (int tableIndex, float note, float phase)
Process with linear interpolation using a specific table index.
Detailed Description
Wrapper around juce::OwnedArray<BandLimitedLookupTable> for managing multiple wavetables.
Constructor & Destructor Documentation
Wavetable() [1/2]
Wavetable::Wavetable () default
Wavetable() [2/2]
Wavetable::Wavetable (Wavetable && other) noexcept
Move constructor.
Member Function Documentation
operator=()
Wavetable & Wavetable::operator= (Wavetable && other) noexcept
Move assignment operator.
addTable()
void Wavetable::addTable (BandLimitedLookupTable * table)
Add a new BandLimitedLookupTable to the collection.
getNumTables()
int Wavetable::getNumTables () const
Get the number of tables.
getTable() [1/2]
BandLimitedLookupTable * Wavetable::getTable (int index)
Get a table by index.
getTable() [2/2]
const BandLimitedLookupTable * Wavetable::getTable (int index) const
Get a table by index (const version)
operator[]() [1/2]
BandLimitedLookupTable * Wavetable::operator[] (int index)
Array subscript operator for compatibility with OwnedArray usage.
operator[]() [2/2]
const BandLimitedLookupTable * Wavetable::operator[] (int index) const
Array subscript operator for compatibility with OwnedArray usage (const version)
getUnchecked() [1/2]
BandLimitedLookupTable * Wavetable::getUnchecked (int index)
Get unchecked access to a table (for compatibility with OwnedArray)
Referenced by WTOscillator::processAddingComplex(), WTOscillator::processAddingCrossfadeComplex(), and WTOscillator::processAddingSimple().
getUnchecked() [2/2]
const BandLimitedLookupTable * Wavetable::getUnchecked (int index) const
Get unchecked access to a table (for compatibility with OwnedArray, const version)
size()
int Wavetable::size () const
Get the number of tables (for compatibility with OwnedArray::size())
Referenced by WTOscillator::processAddingComplex(), WTOscillator::processAddingCrossfadeComplex(), and WTOscillator::processAddingSimple().
clear()
void Wavetable::clear ()
Clear all tables.
process()
float Wavetable::process (int tableIndex, float note, float phase)
Process using a specific table index.
processLinear()
float Wavetable::processLinear (int tableIndex, float note, float phase)
Process with linear interpolation using a specific table index.
The documentation for this class was generated from the following file:
gin_wavetable.h