Gin: Parameter::Listener Class Reference
Parameter::Listener Class Reference abstract
gin_plugin » plugin
Public Member Functions
virtual ~Listener ()
virtual void parameterChanged (Parameter *param)=0
Constructor & Destructor Documentation
~Listener()
virtual Parameter::Listener::~Listener () virtual
References Parameter::addListener(), parameterChanged(), and Parameter::removeListener().
Member Function Documentation
parameterChanged()
virtual void Parameter::Listener::parameterChanged (Parameter * param) pure virtual
Implemented in PluginSlider, PluginComboBox, MultiParamComponent, and PluginButton.
Referenced by ~Listener().
The documentation for this class was generated from the following file:
gin_parameter.h