Gin: ModulationOverview Class Reference
ModulationOverview Class Reference
gin_plugin » components
A button and text readout that shows the current modulation source.
#include <gin_modulation.h>
Public Member Functions
ModulationOverview (ModMatrix &mm)
~ModulationOverview () override
Detailed Description
A button and text readout that shows the current modulation source.
Constructor & Destructor Documentation
ModulationOverview()
ModulationOverview::ModulationOverview (ModMatrix & mm)
References addAndMakeVisible(), ModMatrix::addListener(), and ModMatrix::getLearn().
~ModulationOverview()
ModulationOverview::~ModulationOverview () override
References ModMatrix::removeListener().
The documentation for this class was generated from the following file:
gin_plugin/components/gin_modulation.h