Gin: PluginSlider Class Reference
PluginSlider Class Reference
gin_plugin » components
A slider for controlling a parameter.
Public Member Functions
PluginSlider (Parameter *parameter_, SliderStyle style, TextEntryBoxPosition textBoxPosition)
~PluginSlider () override
void sliderValueChanged (Slider *) override
void sliderDragStarted (Slider *) override
void sliderDragEnded (Slider *) override
void parameterChanged (Parameter *) override
void mouseDown (const MouseEvent &e) override
void mouseUp (const MouseEvent &e) override
void mouseDrag (const MouseEvent &e) override
Detailed Description
A slider for controlling a parameter.
Constructor & Destructor Documentation
PluginSlider()
PluginSlider::PluginSlider (Parameter * parameter_, SliderStyle style, TextEntryBoxPosition textBoxPosition)
References Parameter::addListener(), Parameter::getUserRangeEnd(), Parameter::getUserRangeStart(), Parameter::getUserValue(), and PluginButton::parameter.
~PluginSlider()
PluginSlider::~PluginSlider () override
References PluginButton::parameter, and Parameter::removeListener().
Member Function Documentation
sliderValueChanged()
void PluginSlider::sliderValueChanged (Slider *) override
References Parameter::getUserValue(), PluginButton::parameter, and Parameter::setUserValueNotifingHost().
sliderDragStarted()
void PluginSlider::sliderDragStarted (Slider *) override
References Parameter::beginUserAction(), and PluginButton::parameter.
sliderDragEnded()
void PluginSlider::sliderDragEnded (Slider *) override
References Parameter::endUserAction(), and PluginButton::parameter.
parameterChanged()
void PluginSlider::parameterChanged (Parameter *) override virtual
Implements Parameter::Listener.
References Parameter::getUserValue(), and PluginButton::parameter.
mouseDown()
void PluginSlider::mouseDown (const MouseEvent & e) override
References Parameter::getUserDefaultValue(), PluginButton::parameter, and Parameter::setUserValueNotifingHost().
mouseUp()
void PluginSlider::mouseUp (const MouseEvent & e) override
mouseDrag()
void PluginSlider::mouseDrag (const MouseEvent & e) override
References PluginButton::parameter.
The documentation for this class was generated from the following file:
gin_plugincomponents.h