Gin: ModulationSourceButton Class Reference
ModulationSourceButton Class Reference
gin_plugin » components
A button for enabling modulation learn.
Public Member Functions
ModulationSourceButton (ModMatrix &mm, ModSrcId src={}, bool poly_=false)
~ModulationSourceButton () override
void setSource (ModSrcId src, bool p)
Detailed Description
A button for enabling modulation learn.
Constructor & Destructor Documentation
ModulationSourceButton()
ModulationSourceButton::ModulationSourceButton (ModMatrix & mm, ModSrcId src = {}, bool poly_ = false)
References ModMatrix::addListener().
~ModulationSourceButton()
ModulationSourceButton::~ModulationSourceButton () override
References ModMatrix::removeListener().
Member Function Documentation
setSource()
void ModulationSourceButton::setSource (ModSrcId src, bool p)
References ModMatrix::disableLearn(), ModMatrix::enableLearn(), ModMatrix::getLearn(), ModMatrix::getModSrcName(), and ModSrcId::isValid().
The documentation for this class was generated from the following file:
gin_plugin/components/gin_modulation.h