Gin: FileSystemWatcher::Listener Class Reference
FileSystemWatcher::Listener Class Reference
gin » utilities
Receives callbacks from the FileSystemWatcher when a file changes.
Public Member Functions
virtual ~Listener ()=default
virtual void folderChanged (const juce::File)
virtual void fileChanged (const juce::File, FileSystemEvent)
Detailed Description
Receives callbacks from the FileSystemWatcher when a file changes.
Constructor & Destructor Documentation
~Listener()
virtual FileSystemWatcher::Listener::~Listener () virtual default
Member Function Documentation
folderChanged()
virtual void FileSystemWatcher::Listener::folderChanged (const juce::File) virtual
Referenced by fileChanged().
fileChanged()
virtual void FileSystemWatcher::Listener::fileChanged (const juce::File , FileSystemEvent) virtual
References FileSystemWatcher::addListener(), folderChanged(), and FileSystemWatcher::removeListener().
The documentation for this class was generated from the following file:
gin_filesystemwatcher.h