Gin: PlateReverb< F, I > Class Template Reference
PlateReverb< F, I > Class Template Reference
gin_dsp » dsp
Plate reverb from Dattorro's paper.
#include <gin_platereverb.h>
Public Member Functions
PlateReverb ()
~PlateReverb ()
void setSampleRate (F sampleRate_)
void setMix (F m)
void setPredelay (F pd)
void setLowpass (F cutoff)
void setDecay (F dr)
void setSize (F sz)
void setDamping (F cutoff)
void process (F dryLeft, F dryRight, F *leftOut, F *rightOut)
void process (F *l, F *r, I num)
void reset ()
Static Public Attributes
static constexpr F kMaxPredelay = F (0.1)
static constexpr F kMaxSize = 2.0
Detailed Description
template<class F, class I>
class PlateReverb< F, I >
Plate reverb from Dattorro's paper.
Constructor & Destructor Documentation
PlateReverb()
template<class F , class I > PlateReverb< F, I >::PlateReverb ()
~PlateReverb()
template<class F , class I > PlateReverb< F, I >::~PlateReverb ()
Member Function Documentation
setSampleRate()
template<class F , class I > void PlateReverb< F, I >::setSampleRate (F sampleRate_)
References PlateReverb< F, I >::kMaxPredelay, and PlateReverb< F, I >::kMaxSize.
setMix()
template<class F , class I > void PlateReverb< F, I >::setMix (F m)
setPredelay()
template<class F , class I > void PlateReverb< F, I >::setPredelay (F pd)
References PlateReverb< F, I >::kMaxPredelay.
setLowpass()
template<class F , class I > void PlateReverb< F, I >::setLowpass (F cutoff)
setDecay()
template<class F , class I > void PlateReverb< F, I >::setDecay (F dr)
setSize()
template<class F , class I > void PlateReverb< F, I >::setSize (F sz)
References PlateReverb< F, I >::kMaxSize.
setDamping()
template<class F , class I > void PlateReverb< F, I >::setDamping (F cutoff)
process() [1/2]
template<class F , class I > void PlateReverb< F, I >::process (F dryLeft, F dryRight, F * leftOut, F * rightOut)
Referenced by PlateReverb< F, I >::process().
process() [2/2]
template<class F , class I > void PlateReverb< F, I >::process (F * l, F * r, I num)
References PlateReverb< F, I >::process().
reset()
template<class F , class I > void PlateReverb< F, I >::reset ()
Member Data Documentation
kMaxPredelay
template<class F , class I > constexpr F PlateReverb< F, I >::kMaxPredelay = F (0.1) static constexpr
Referenced by PlateReverb< F, I >::setPredelay(), and PlateReverb< F, I >::setSampleRate().
kMaxSize
template<class F , class I > constexpr F PlateReverb< F, I >::kMaxSize = 2.0 static constexpr
Referenced by PlateReverb< F, I >::setSampleRate(), and PlateReverb< F, I >::setSize().
The documentation for this class was generated from the following file:
gin_platereverb.h