Gin: WTOscillator Class Reference
WTOscillator Class Reference
gin_dsp » dsp
Wavetable oscillator with interpolation and shaping options.
#include <gin_wtoscillators.h>
Classes
struct Params
Public Member Functions
WTOscillator ()=default
void setSampleRate (double sr)
void noteOn (float p=-1)
void process (float note, const Params &params, juce::AudioSampleBuffer &buffer)
void processAdding (float note, const Params &params, juce::AudioSampleBuffer &buffer)
void processAddingSimple (float note, const Params &params, juce::AudioSampleBuffer &buffer)
void processAddingComplex (float note, const Params &params, juce::AudioSampleBuffer &buffer)
void processAddingCrossfadeComplex (float note, const Params &params, juce::AudioSampleBuffer &buffer)
template<typename T >
void postProcess (const Params &params, T &v)
void setWavetable (Wavetable *table)
void setBlockDC (bool b)
Detailed Description
Wavetable oscillator with interpolation and shaping options.
WTOscillator provides high-quality wavetable synthesis with support for table morphing, formant shifting, phase distortion (bend), and post-processing effects like asymmetry and wavefolding. It uses band-limited wavetables to avoid aliasing.
Key Features:
Wavetable synthesis with linear interpolation
Table position morphing for timbral variation
Formant shifting (pitch-independent spectral shift)
Phase distortion (bend parameter)
Wavefolding and asymmetry effects
Optional DC blocking
SIMD optimization where available
Parameters (via Params struct):
position: Wavetable position (0.0 to 1.0)
bend: Phase distortion amount
formant: Formant shift (pitch-independent frequency shift)
asym: Asymmetry/waveshaping amount
fold: Wavefolding amount
leftGain/rightGain: Stereo output gains
Usage:
WTOscillator osc;
osc.setSampleRate(44100.0);
osc.setWaveTable(&myBandLimitedTables);
osc.noteOn(); // Initialize phase
WTOscillator::Params params;
params.position = 0.3f;
params.fold = 0.2f;
osc.process(60.0f, params, audioBuffer); // MIDI note 60 (C4)
See also
BandLimitedLookupTable, DCBlocker
Constructor & Destructor Documentation
WTOscillator()
WTOscillator::WTOscillator () default
Member Function Documentation
setSampleRate()
void WTOscillator::setSampleRate (double sr)
References DCBlocker::setCutoff(), and DCBlocker::setSampleRate().
noteOn()
void WTOscillator::noteOn (float p = -1)
process()
void WTOscillator::process (float note, const Params & params, juce::AudioSampleBuffer & buffer)
References processAdding().
processAdding()
void WTOscillator::processAdding (float note, const Params & params, juce::AudioSampleBuffer & buffer)
References WTOscillator::Params::bend, WTOscillator::Params::formant, DCBlocker::process(), processAddingComplex(), processAddingCrossfadeComplex(), and processAddingSimple().
Referenced by process().
processAddingSimple()
void WTOscillator::processAddingSimple (float note, const Params & params, juce::AudioSampleBuffer & buffer)
References Wavetable::getUnchecked(), WTOscillator::Params::leftGain, math::min(), WTOscillator::Params::position, postProcess(), WTOscillator::Params::rightGain, and Wavetable::size().
Referenced by processAdding().
processAddingComplex()
void WTOscillator::processAddingComplex (float note, const Params & params, juce::AudioSampleBuffer & buffer)
References WTOscillator::Params::bend, WTOscillator::Params::formant, Wavetable::getUnchecked(), WTOscillator::Params::leftGain, math::min(), WTOscillator::Params::position, postProcess(), WTOscillator::Params::rightGain, and Wavetable::size().
Referenced by processAdding().
processAddingCrossfadeComplex()
void WTOscillator::processAddingCrossfadeComplex (float note, const Params & params, juce::AudioSampleBuffer & buffer)
References WTOscillator::Params::bend, WTOscillator::Params::formant, Wavetable::getUnchecked(), WTOscillator::Params::leftGain, math::min(), WTOscillator::Params::position, postProcess(), WTOscillator::Params::rightGain, and Wavetable::size().
Referenced by processAdding().
postProcess()
template<typename T > void WTOscillator::postProcess (const Params & params, T & v)
References WTOscillator::Params::asym, WTOscillator::Params::fold, math::lerp(), math::max(), math::min(), math::pow2(), and math::pow4().
Referenced by processAddingComplex(), processAddingCrossfadeComplex(), and processAddingSimple().
setWavetable()
void WTOscillator::setWavetable (Wavetable * table)
setBlockDC()
void WTOscillator::setBlockDC (bool b)
The documentation for this class was generated from the following file:
gin_wtoscillators.h