Gin: DCBlocker Class Reference
DCBlocker Class Reference
gin_dsp » dsp
DC blocking filter (high-pass filter) to remove DC offset.
#include <gin_wtoscillators.h>
Public Member Functions
DCBlocker ()
~DCBlocker ()
void setSampleRate (float sampleRate_)
void setCutoff (float cutoff_)
float process (float x)
void reset ()
Detailed Description
DC blocking filter (high-pass filter) to remove DC offset.
DCBlocker implements a simple first-order high-pass filter to remove DC offset from audio signals. This is useful after certain DSP operations (like waveshaping or oscillators) that may introduce DC bias.
Key Features:
Configurable cutoff frequency (default 10 Hz)
First-order IIR filter
Very low CPU usage
Reset for clearing filter state
Usage:
DCBlocker blocker;
blocker.setSampleRate(44100.0f);
blocker.setCutoff(10.0f); // Block below 10 Hz
// Per-sample processing
float output = blocker.process(input);
Note: This is a per-sample filter. For stereo, use two instances.
See also
WTOscillator
Constructor & Destructor Documentation
DCBlocker()
DCBlocker::DCBlocker ()
~DCBlocker()
DCBlocker::~DCBlocker ()
Member Function Documentation
setSampleRate()
void DCBlocker::setSampleRate (float sampleRate_)
Referenced by WTOscillator::setSampleRate().
setCutoff()
void DCBlocker::setCutoff (float cutoff_)
Referenced by WTOscillator::setSampleRate().
process()
float DCBlocker::process (float x)
Referenced by WTOscillator::processAdding().
reset()
void DCBlocker::reset ()
The documentation for this class was generated from the following file:
gin_wtoscillators.h