Gin: MultiParamComponent Class Reference
MultiParamComponent Class Reference
gin_plugin » components
A base component for controlling multiple parameters at once.
#include <gin_multiparamcomponent.h>
Public Member Functions
MultiParamComponent ()
~MultiParamComponent () override
juce::Colour dimIfNeeded (const juce::Colour &c)
Public Member Functions inherited from Parameter::ParameterListener
virtual ~ParameterListener ()
Protected Member Functions
void showBubble (const juce::String &text, const juce::Rectangle< int > &rc)
void hideBubble ()
void watchParam (Parameter *p)
void unwatchParam (Parameter *p)
void unwatchParams ()
virtual void paramChanged ()
void enablementChanged () override
void valueUpdated (Parameter *) override
void handleAsyncUpdate () override
Protected Attributes
juce::Array< Parameter * > params
std::unique_ptr< juce::BubbleMessageComponent > bubble
Detailed Description
A base component for controlling multiple parameters at once.
Constructor & Destructor Documentation
MultiParamComponent()
MultiParamComponent::MultiParamComponent ()
~MultiParamComponent()
MultiParamComponent::~MultiParamComponent () override
References unwatchParams().
Member Function Documentation
dimIfNeeded()
juce::Colour MultiParamComponent::dimIfNeeded (const juce::Colour & c)
showBubble()
void MultiParamComponent::showBubble (const juce::String & text, const juce::Rectangle< int > & rc) protected
References bubble.
hideBubble()
void MultiParamComponent::hideBubble () protected
References bubble.
watchParam()
void MultiParamComponent::watchParam (Parameter * p) protected
References Parameter::addListener(), and params.
Referenced by ParamBox::addEnable(), ParamBox::addHeader(), and PagedControlBox::addPageEnable().
unwatchParam()
void MultiParamComponent::unwatchParam (Parameter * p) protected
References params, and Parameter::removeListener().
unwatchParams()
void MultiParamComponent::unwatchParams () protected
References params.
Referenced by ~MultiParamComponent().
paramChanged()
virtual void MultiParamComponent::paramChanged () protected virtual
Reimplemented in PagedControlBox, and ParamBox.
Referenced by handleAsyncUpdate(), PagedControlBox::paramChanged(), and ParamBox::paramChanged().
enablementChanged()
void MultiParamComponent::enablementChanged () override protected
valueUpdated()
void MultiParamComponent::valueUpdated (Parameter *) override protected virtual
Implements Parameter::ParameterListener.
handleAsyncUpdate()
void MultiParamComponent::handleAsyncUpdate () override protected
References paramChanged().
Member Data Documentation
params
juce::Array<Parameter*> MultiParamComponent::params protected
Referenced by unwatchParam(), unwatchParams(), and watchParam().
bubble
std::unique_ptr<juce::BubbleMessageComponent> MultiParamComponent::bubble protected
Referenced by hideBubble(), and showBubble().
The documentation for this class was generated from the following file:
gin_multiparamcomponent.h