Gin: RetrospectiveBufferComponent Class Reference
RetrospectiveBufferComponent Class Reference
gin_standaloneplugin » standaloneplugin
#include <gin_sidebarcomponent.h>
Public Member Functions
RetrospectiveBufferComponent (AudioRecorder &recorder)
~RetrospectiveBufferComponent () override
void timerCallback () override
void paint (juce::Graphics &g) override
Public Member Functions inherited from AudioSamplerBufferComponent
AudioSamplerBufferComponent ()
~AudioSamplerBufferComponent () override
void setBuffer (const juce::AudioSampleBuffer &)
const juce::AudioBuffer< float > & getBuffer ()
void clear ()
void setScrollable (bool s)
int getLength ()
void setHiResDisabled (bool b)
float getViewLeft ()
float getViewRight ()
void scrollViewBounds (float delta)
void setViewLeft (float left)
void setViewRight (float right)
void setViewBounds (float left, float right)
void setMaxZoom (float maxZoom)
void zoom (float centrePoint, float factor)
void setPlayheads (const std::vector< int > &playheads)
float xToSample (float x)
float sampleToX (int sample)
int lengthInSamples ()
void setLineColour (juce::Colour c)
void setBackgroundColour (juce::Colour c)
void paint (juce::Graphics &) override
void resized () override
void mouseWheelMove (const juce::MouseEvent &e, const juce::MouseWheelDetails &wheel) override
juce::MouseCursor getMouseCursor () override
void mouseDown (const juce::MouseEvent &e) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &e) override
Additional Inherited Members
Protected Member Functions inherited from AudioSamplerBufferComponent
void paintBackground (juce::Graphics &g)
void paintPlayheads (juce::Graphics &g)
void paintChannelData (juce::Graphics &g, int channel, const juce::Rectangle< float > &r)
Constructor & Destructor Documentation
RetrospectiveBufferComponent()
RetrospectiveBufferComponent::RetrospectiveBufferComponent (AudioRecorder & recorder)
~RetrospectiveBufferComponent()
RetrospectiveBufferComponent::~RetrospectiveBufferComponent () override
Member Function Documentation
timerCallback()
void RetrospectiveBufferComponent::timerCallback () override
References AudioRecorder::getRetrospectiveNumChannels(), AudioRecorder::getRetrospectiveNumReady(), AudioRecorder::peekRetrospective(), and AudioSamplerBufferComponent::setBuffer().
paint()
void RetrospectiveBufferComponent::paint (juce::Graphics & g) override
References GinLookAndFeel::grey45ColourId, and AudioSamplerBufferComponent::paint().
The documentation for this class was generated from the following file:
gin_sidebarcomponent.h