Gin: BandLimitedLookupTables Class Reference
BandLimitedLookupTables Class Reference
gin_dsp » dsp
Generate and hold bandlimited lookup tables for all the common waveforms.
#include <gin_bandlimitedlookuptable.h>
Public Member Functions
BandLimitedLookupTables (double sampleRate=44100, int notesPerTable=3, int tableSize=2048)
void setSampleRate (double sampleRate)
float processSine (float phase)
float processTriangle (float note, float phase)
float processSawUp (float note, float phase)
float processSawDown (float note, float phase)
float processSquare (float note, float phase)
float processPulse (float note, float phase, float pw)
float process (Wave wave, float note, float phase, float pw)
double getSampleRate ()
Detailed Description
Generate and hold bandlimited lookup tables for all the common waveforms.
Constructor & Destructor Documentation
BandLimitedLookupTables()
BandLimitedLookupTables::BandLimitedLookupTables (double sampleRate = 44100, int notesPerTable = 3, int tableSize = 2048)
Member Function Documentation
setSampleRate()
void BandLimitedLookupTables::setSampleRate (double sampleRate)
processSine()
float BandLimitedLookupTables::processSine (float phase)
References BandLimitedLookupTable::getLinear().
Referenced by process().
processTriangle()
float BandLimitedLookupTables::processTriangle (float note, float phase)
References BandLimitedLookupTable::getLinear(), BandLimitedLookupTable::notesPerTable, and BandLimitedLookupTable::tables.
Referenced by process().
processSawUp()
float BandLimitedLookupTables::processSawUp (float note, float phase)
References BandLimitedLookupTable::getLinear(), BandLimitedLookupTable::notesPerTable, and BandLimitedLookupTable::tables.
Referenced by process().
processSawDown()
float BandLimitedLookupTables::processSawDown (float note, float phase)
References BandLimitedLookupTable::getLinear(), BandLimitedLookupTable::notesPerTable, and BandLimitedLookupTable::tables.
Referenced by process().
processSquare()
float BandLimitedLookupTables::processSquare (float note, float phase)
References BandLimitedLookupTable::getLinear(), and BandLimitedLookupTable::tables.
Referenced by process().
processPulse()
float BandLimitedLookupTables::processPulse (float note, float phase, float pw)
References BandLimitedLookupTable::getLinear(), and BandLimitedLookupTable::tables.
Referenced by process().
process()
float BandLimitedLookupTables::process (Wave wave, float note, float phase, float pw)
References WhiteNoise::nextSample(), PinkNoise::nextSample(), pinkNoise, processPulse(), processSawDown(), processSawUp(), processSine(), processSquare(), processTriangle(), pulse, sawDown, sawUp, silence, sine, square, triangle, and whiteNoise.
Referenced by StereoOscillator::processAdding().
getSampleRate()
double BandLimitedLookupTables::getSampleRate ()
The documentation for this class was generated from the following file:
gin_bandlimitedlookuptable.h