Gin: ImageMetadata Class Reference
ImageMetadata Class Reference abstract
gin_metadata » metadata
Public Member Functions
ImageMetadata (const String &type)
virtual ~ImageMetadata ()
String getType () const
virtual StringPairArray getAllMetadata () const =0
Static Public Member Functions
static bool getFromImage (InputStream &is, OwnedArray< ImageMetadata > &metadata)
Protected Attributes
String type
Constructor & Destructor Documentation
ImageMetadata()
ImageMetadata::ImageMetadata (const String & type)
~ImageMetadata()
virtual ImageMetadata::~ImageMetadata () virtual
Member Function Documentation
getType()
String ImageMetadata::getType () const
References getAllMetadata(), getFromImage(), and type.
getAllMetadata()
virtual StringPairArray ImageMetadata::getAllMetadata () const pure virtual
Implemented in XmpMetadata, CommentMetadata, ExifMetadata, and IptcMetadata.
Referenced by getType().
getFromImage()
static bool ImageMetadata::getFromImage (InputStream & is, OwnedArray< ImageMetadata > & metadata) static
Referenced by getType().
Member Data Documentation
type
String ImageMetadata::type protected
Referenced by getType().
The documentation for this class was generated from the following file:
gin_imagemetadata.h