Gin: AudioRecorder Class Reference
AudioRecorder Class Reference
gin_standaloneplugin » standaloneplugin
#include <gin_standaloneaudioprocessorplayer.h>
Inherits juce::Thread.
Public Types
enum class RecordMode { idle , normal , triggered , waitingForTrigger }
Public Member Functions
AudioRecorder (AudioFifo &f)
~AudioRecorder () override
void setSampleRate (double sr)
void setDestFolder (const juce::File &folder)
juce::File getDestFolder () const
void startRecording ()
void startTriggeredRecording ()
void stopRecording ()
bool isRecording () const
bool isWaitingForTrigger () const
RecordMode getRecordMode () const
void saveRetrospective ()
int getRetrospectiveNumReady () const
int getRetrospectiveNumChannels () const
bool peekRetrospective (juce::AudioSampleBuffer &dest)
void clearRetrospective ()
void run () override
Public Attributes
std::function< void()> onRecordingStarted
std::function< void()> onRecordingStopped
Member Enumeration Documentation
RecordMode
enum class AudioRecorder::RecordMode strong
Enumerator
idle
normal
triggered
waitingForTrigger
Constructor & Destructor Documentation
AudioRecorder()
AudioRecorder::AudioRecorder (AudioFifo & f)
~AudioRecorder()
AudioRecorder::~AudioRecorder () override
References stopRecording().
Member Function Documentation
setSampleRate()
void AudioRecorder::setSampleRate (double sr)
References AudioFifo::getNumChannels(), and AudioFifo::setSize().
Referenced by StandaloneAudioProcessorPlayer::audioDeviceAboutToStart().
setDestFolder()
void AudioRecorder::setDestFolder (const juce::File & folder)
getDestFolder()
juce::File AudioRecorder::getDestFolder () const
startRecording()
void AudioRecorder::startRecording ()
References idle, and normal.
startTriggeredRecording()
void AudioRecorder::startTriggeredRecording ()
References idle, and waitingForTrigger.
stopRecording()
void AudioRecorder::stopRecording ()
References idle.
Referenced by ~AudioRecorder().
isRecording()
bool AudioRecorder::isRecording () const
References normal, and triggered.
isWaitingForTrigger()
bool AudioRecorder::isWaitingForTrigger () const
References waitingForTrigger.
getRecordMode()
RecordMode AudioRecorder::getRecordMode () const
saveRetrospective()
void AudioRecorder::saveRetrospective ()
References AudioFifo::getNumChannels(), AudioFifo::getNumReady(), and AudioFifo::peek().
getRetrospectiveNumReady()
int AudioRecorder::getRetrospectiveNumReady () const
References AudioFifo::getNumReady().
Referenced by RetrospectiveBufferComponent::timerCallback().
getRetrospectiveNumChannels()
int AudioRecorder::getRetrospectiveNumChannels () const
References AudioFifo::getNumChannels().
Referenced by RetrospectiveBufferComponent::timerCallback().
peekRetrospective()
bool AudioRecorder::peekRetrospective (juce::AudioSampleBuffer & dest)
References AudioFifo::peek().
Referenced by RetrospectiveBufferComponent::timerCallback().
clearRetrospective()
void AudioRecorder::clearRetrospective ()
References AudioFifo::reset().
run()
void AudioRecorder::run () override
References AudioFifo::ensureFreeSpace(), AudioFifo::getNumChannels(), AudioFifo::getNumReady(), normal, onRecordingStarted, AudioFifo::peek(), AudioFifo::read(), triggered, waitingForTrigger, and AudioFifo::write().
Member Data Documentation
onRecordingStarted
std::function<void()> AudioRecorder::onRecordingStarted
Referenced by run().
onRecordingStopped
std::function<void()> AudioRecorder::onRecordingStopped
The documentation for this class was generated from the following file:
gin_standaloneaudioprocessorplayer.h