Gin: SampleFileComponent Class Reference
SampleFileComponent Class Reference
gin_standaloneplugin » standaloneplugin
#include <gin_sidebarcomponent.h>
Public Member Functions
SampleFileComponent (SamplePlayer &player)
~SampleFileComponent () override
void timerCallback () override
bool isInterestedInFileDrag (const juce::StringArray &files) override
void fileDragEnter (const juce::StringArray &, int, int) override
void fileDragExit (const juce::StringArray &) override
void filesDropped (const juce::StringArray &files, int, int) override
void paint (juce::Graphics &g) override
Public Member Functions inherited from AudioSamplerBufferComponent
AudioSamplerBufferComponent ()
~AudioSamplerBufferComponent () override
void setBuffer (const juce::AudioSampleBuffer &)
const juce::AudioBuffer< float > & getBuffer ()
void clear ()
void setScrollable (bool s)
int getLength ()
void setHiResDisabled (bool b)
float getViewLeft ()
float getViewRight ()
void scrollViewBounds (float delta)
void setViewLeft (float left)
void setViewRight (float right)
void setViewBounds (float left, float right)
void setMaxZoom (float maxZoom)
void zoom (float centrePoint, float factor)
void setPlayheads (const std::vector< int > &playheads)
float xToSample (float x)
float sampleToX (int sample)
int lengthInSamples ()
void setLineColour (juce::Colour c)
void setBackgroundColour (juce::Colour c)
void paint (juce::Graphics &) override
void resized () override
void mouseWheelMove (const juce::MouseEvent &e, const juce::MouseWheelDetails &wheel) override
juce::MouseCursor getMouseCursor () override
void mouseDown (const juce::MouseEvent &e) override
void mouseDrag (const juce::MouseEvent &e) override
void mouseUp (const juce::MouseEvent &e) override
Public Attributes
std::function< void()> onFileDropped
std::function< void()> onPlaybackStateChanged
Constructor & Destructor Documentation
SampleFileComponent()
SampleFileComponent::SampleFileComponent (SamplePlayer & player)
~SampleFileComponent()
SampleFileComponent::~SampleFileComponent () override
Member Function Documentation
timerCallback()
void SampleFileComponent::timerCallback () override
References SamplePlayer::getPosition(), SamplePlayer::hasFileLoaded(), SamplePlayer::isPlaying(), onPlaybackStateChanged, and AudioSamplerBufferComponent::setPlayheads().
isInterestedInFileDrag()
bool SampleFileComponent::isInterestedInFileDrag (const juce::StringArray & files) override
fileDragEnter()
void SampleFileComponent::fileDragEnter (const juce::StringArray & , int , int) override
fileDragExit()
void SampleFileComponent::fileDragExit (const juce::StringArray &) override
filesDropped()
void SampleFileComponent::filesDropped (const juce::StringArray & files, int , int) override
References SamplePlayer::getBuffer(), SamplePlayer::load(), onFileDropped, and AudioSamplerBufferComponent::setBuffer().
paint()
void SampleFileComponent::paint (juce::Graphics & g) override
References GinLookAndFeel::accentColourId, GinLookAndFeel::grey45ColourId, and AudioSamplerBufferComponent::paint().
Member Data Documentation
onFileDropped
std::function<void()> SampleFileComponent::onFileDropped
Referenced by filesDropped().
onPlaybackStateChanged
std::function<void()> SampleFileComponent::onPlaybackStateChanged
Referenced by timerCallback().
The documentation for this class was generated from the following file:
gin_sidebarcomponent.h