Gin: ModCurveButton Class Reference
ModCurveButton Class Reference
gin_plugin » components
A button that displays mod curve.
#include <gin_modulation.h>
Inherits juce::Button.
Public Member Functions
ModCurveButton ()
void setCurve (ModMatrix::Function c)
void paintButton (juce::Graphics &g, bool over, bool down) override
Detailed Description
A button that displays mod curve.
Constructor & Destructor Documentation
ModCurveButton()
ModCurveButton::ModCurveButton ()
Member Function Documentation
setCurve()
void ModCurveButton::setCurve (ModMatrix::Function c)
paintButton()
void ModCurveButton::paintButton (juce::Graphics & g, bool over, bool down) override
References GinLookAndFeel::accentColourId, Point< T >::getX(), Point< T >::getY(), ModMatrix::shape(), and GinLookAndFeel::whiteColourId.
The documentation for this class was generated from the following file:
gin_plugin/components/gin_modulation.h