Gin: PluginComboBox Class Reference
PluginComboBox Class Reference
A control for selecting param values from a dropbox.
Public Member Functions
PluginComboBox (Parameter *parameter_)
~PluginComboBox () override
void parameterChanged (Parameter *) override
void comboBoxChanged (ComboBox *) override
Public Attributes
Parameter * parameter
Detailed Description
A control for selecting param values from a dropbox.
Constructor & Destructor Documentation
PluginComboBox()
PluginComboBox::PluginComboBox (Parameter * parameter_)
References Parameter::addListener(), Parameter::getUserRangeEnd(), Parameter::getUserRangeStart(), Parameter::getUserValue(), parameter, and Parameter::userValueToText().
~PluginComboBox()
PluginComboBox::~PluginComboBox () override
References parameter, and Parameter::removeListener().
Member Function Documentation
parameterChanged()
void PluginComboBox::parameterChanged (Parameter *) override virtual
Implements Parameter::Listener.
References Parameter::getUserRangeStart(), Parameter::getUserValue(), and parameter.
comboBoxChanged()
void PluginComboBox::comboBoxChanged (ComboBox *) override
References Parameter::beginUserAction(), Parameter::endUserAction(), Parameter::getUserRangeStart(), parameter, and Parameter::setUserValueNotifingHost().
Member Data Documentation
parameter
Parameter* PluginComboBox::parameter
Referenced by comboBoxChanged(), parameterChanged(), PluginComboBox(), and ~PluginComboBox().
The documentation for this class was generated from the following file:
gin_plugincomponents.h