Gin: Parameter Class Reference
Parameter Class Reference
gin_plugin » plugin
Advanced parameter class with modulation, real-time callbacks, and host automation.
#include <gin_parameter.h>
Inherits juce::AudioPluginInstance::HostedParameter, juce::AsyncUpdater, and juce::Timer.
Classes
class ParameterListener
struct ParamState
Public Types
using Ptr = Parameter *
Public Member Functions
Parameter (Processor &, juce::String uid, juce::String name, juce::String shortName, juce::String label, float minValue, float maxValue, float intervalValue, float defaultValue, float skewFactor=1.0f, std::function< juce::String(const Parameter &, float)> textFunction=nullptr)
Parameter (Processor &, juce::String uid, juce::String name, juce::String shortName, juce::String label, juce::NormalisableRange< float > range, float defaultValue, std::function< juce::String(const Parameter &, float)> textFunction=nullptr)
juce::String getUid () const
void setInternal (bool i)
bool isInternal () const
void setModIndex (int i)
int getModIndex () const
void setModMatrix (ModMatrix *m)
ModMatrix * getModMatrix () const
virtual void prepareToPlay (double, int)
virtual void reset ()
float getProcValue ()
virtual float getProcValue (int)
float getUserValue () const
int getUserValueInt () const
bool getUserValueBool () const
float getUserDefaultValue () const
virtual void setUserValue (float v)
virtual void setUserValueNotifingHost (float f)
void setUserValueAsUserAction (float f)
juce::String getUserValueText () const
juce::String userValueToText (float val)
bool isOnOff ()
bool isOn ()
virtual bool isSmoothingActive ()
void beginUserAction ()
void beginUserTimedAction ()
void endUserAction ()
juce::NormalisableRange< float > getUserRange () const
float getUserRangeStart () const
float getUserRangeEnd () const
void addListener (ParameterListener *listener)
void removeListener (ParameterListener *listener)
ParamState getState ()
void setState (const ParamState &state)
juce::String getParameterID () const override
float getValue () const override
bool getBoolValue () const
void setValue (float newValue) override
float getDefaultValue () const override
juce::String getName (int maximumStringLength) const override
juce::String getShortName () const
juce::String getLabel () const override
int getNumSteps () const override
juce::String getText (float value, int) const override
float getValueForText (const juce::String &text) const override
bool isOrientationInverted () const override
bool isAutomatable () const override
bool isMetaParameter () const override
float getSkew ()
bool isSkewSymmetric ()
Public Attributes
std::function< float(float)> conversionFunction
Protected Member Functions
void handleAsyncUpdate () override
void timerCallback () override
virtual void changed ()
Protected Attributes
Processor & processor
const juce::NormalisableRange< float > range
bool internal = false
ModMatrix * modMatrix = nullptr
int modIndex = -1
std::atomic< float > value {0.0f}
const float defaultValue = 0.0f
const juce::String uid
const juce::String name
const juce::String shortName
const juce::String label
const std::function< juce::String(const Parameter &, float)> textFunction
int userActionCount = 0
juce::ListenerList< ParameterListener > listeners
Detailed Description
Advanced parameter class with modulation, real-time callbacks, and host automation.
Parameter provides a comprehensive plugin parameter implementation with features needed for professional audio plugins. It extends JUCE's parameter system with modulation support, user/processing value separation, and real-time safe callbacks.
Value Formats: Parameter values are represented in three formats:
value: Normalized 0..1 range (for host automation)
user value: Range as displayed to user (e.g., -100 to +10 dB)
proc value: Range used for DSP processing (e.g., 0 to 3.1623 for gain)
By default, user value and proc value are identical. To provide custom processing values, set the conversionFunction (e.g., converting dB to linear gain).
Parameter Types:
External: Exposed to host, can be automated and modulated
Internal: Hidden from host, cannot be modulated (e.g., UI-only settings)
Key Features:
Host automation support
Modulation matrix integration
Real-time safe value callbacks
User action tracking (begin/end gestures)
Custom text formatting
Skewed parameter ranges
Optional parameter smoothing
Listener callbacks for UI updates
Usage:
// Create a gain parameter with dB display but linear processing
auto* gain = new Parameter(processor,
    "gain", "Gain", "Gain", "dB",
    -100.0f, 10.0f,   // User range: -100 to +10 dB
    0.1f,             // Step size
    0.0f,             // Default value
    1.0f);            // No skew
// Convert dB to linear for processing
gain->conversionFunction = [](float db) {
    return juce::Decibels::decibelsToGain(db);
};
// In DSP code
float linearGain = gain->getProcValue();
// In UI
String displayText = gain->getUserValueText(); // "0.0 dB"
See also
Processor, ModMatrix, SmoothedParameter
Member Typedef Documentation
Ptr
using Parameter::Ptr = Parameter*
Constructor & Destructor Documentation
Parameter() [1/2]
Parameter::Parameter (Processor & , juce::String uid, juce::String name, juce::String shortName, juce::String label, float minValue, float maxValue, float intervalValue, float defaultValue, float skewFactor = 1.0f, std::function< juce::String(const Parameter &, float)> textFunction = nullptr)
Parameter() [2/2]
Parameter::Parameter (Processor & , juce::String uid, juce::String name, juce::String shortName, juce::String label, juce::NormalisableRange< float > range, float defaultValue, std::function< juce::String(const Parameter &, float)> textFunction = nullptr)
Member Function Documentation
getUid()
juce::String Parameter::getUid () const
References uid.
Referenced by ParamComponent::getUid().
setInternal()
void Parameter::setInternal (bool i)
References internal.
isInternal()
bool Parameter::isInternal () const
References internal.
setModIndex()
void Parameter::setModIndex (int i)
References modIndex.
getModIndex()
int Parameter::getModIndex () const
References modIndex.
setModMatrix()
void Parameter::setModMatrix (ModMatrix * m)
References modMatrix.
getModMatrix()
ModMatrix * Parameter::getModMatrix () const
References modMatrix.
prepareToPlay()
virtual void Parameter::prepareToPlay (double , int) virtual
reset()
virtual void Parameter::reset () virtual
getProcValue() [1/2]
float Parameter::getProcValue ()
References conversionFunction, and getUserValue().
getProcValue() [2/2]
virtual float Parameter::getProcValue (int) virtual
References conversionFunction, and getUserValue().
getUserValue()
float Parameter::getUserValue () const
References range, and value.
Referenced by PluginButton::clicked(), SVGPluginButton::clicked(), getProcValue(), getProcValue(), isOn(), PluginButton::PluginButton(), PluginComboBox::PluginComboBox(), PluginSlider::PluginSlider(), PluginSlider::sliderValueChanged(), SVGPluginButton::SVGPluginButton(), PluginButton::valueUpdated(), SVGPluginButton::valueUpdated(), PluginComboBox::valueUpdated(), and PluginSlider::valueUpdated().
getUserValueInt()
int Parameter::getUserValueInt () const
References range, and value.
getUserValueBool()
bool Parameter::getUserValueBool () const
References range, and value.
getUserDefaultValue()
float Parameter::getUserDefaultValue () const
References defaultValue.
Referenced by PluginSlider::mouseDown().
setUserValue()
virtual void Parameter::setUserValue (float v) virtual
setUserValueNotifingHost()
virtual void Parameter::setUserValueNotifingHost (float f) virtual
Referenced by PluginButton::clicked(), SVGPluginButton::clicked(), PluginComboBox::comboBoxChanged(), PluginSlider::mouseDown(), and PluginSlider::sliderValueChanged().
setUserValueAsUserAction()
void Parameter::setUserValueAsUserAction (float f)
getUserValueText()
juce::String Parameter::getUserValueText () const
References getText(), getValue(), and label.
Referenced by PluginButton::clicked(), SVGPluginButton::clicked(), PluginButton::PluginButton(), SVGPluginButton::SVGPluginButton(), PluginButton::valueUpdated(), and SVGPluginButton::valueUpdated().
userValueToText()
juce::String Parameter::userValueToText (float val)
References getText(), label, and range.
Referenced by PluginComboBox::PluginComboBox().
isOnOff()
bool Parameter::isOnOff ()
References range.
isOn()
bool Parameter::isOn ()
References getUserValue(), and range.
isSmoothingActive()
virtual bool Parameter::isSmoothingActive () virtual
beginUserAction()
void Parameter::beginUserAction ()
Referenced by PluginButton::clicked(), SVGPluginButton::clicked(), PluginComboBox::comboBoxChanged(), and PluginSlider::sliderDragStarted().
beginUserTimedAction()
void Parameter::beginUserTimedAction ()
endUserAction()
void Parameter::endUserAction ()
Referenced by PluginButton::clicked(), SVGPluginButton::clicked(), PluginComboBox::comboBoxChanged(), and PluginSlider::sliderDragEnded().
getUserRange()
juce::NormalisableRange< float > Parameter::getUserRange () const
References range.
getUserRangeStart()
float Parameter::getUserRangeStart () const
References range.
Referenced by PluginComboBox::comboBoxChanged(), PluginComboBox::PluginComboBox(), PluginSlider::PluginSlider(), and PluginComboBox::valueUpdated().
getUserRangeEnd()
float Parameter::getUserRangeEnd () const
References range.
Referenced by PluginComboBox::PluginComboBox(), and PluginSlider::PluginSlider().
addListener()
void Parameter::addListener (ParameterListener * listener)
Referenced by PluginButton::PluginButton(), PluginComboBox::PluginComboBox(), PluginSlider::PluginSlider(), SVGPluginButton::SVGPluginButton(), and MultiParamComponent::watchParam().
removeListener()
void Parameter::removeListener (ParameterListener * listener)
Referenced by MultiParamComponent::unwatchParam(), PluginButton::~PluginButton(), PluginComboBox::~PluginComboBox(), PluginSlider::~PluginSlider(), and SVGPluginButton::~SVGPluginButton().
getState()
ParamState Parameter::getState ()
setState()
void Parameter::setState (const ParamState & state)
getParameterID()
juce::String Parameter::getParameterID () const override
References uid.
getValue()
float Parameter::getValue () const override
References range, and value.
Referenced by getBoolValue(), and getUserValueText().
getBoolValue()
bool Parameter::getBoolValue () const
References getValue().
setValue()
void Parameter::setValue (float newValue) override
Referenced by SmoothedParameter< T >::SmoothedParameter(), and SmoothedParameter< T >::SmoothedParameter().
getDefaultValue()
float Parameter::getDefaultValue () const override
References defaultValue, and range.
getName()
juce::String Parameter::getName (int maximumStringLength) const override
getShortName()
juce::String Parameter::getShortName () const
References shortName.
Referenced by PluginButton::PluginButton(), and PluginSlider::PluginSlider().
getLabel()
juce::String Parameter::getLabel () const override
References label.
getNumSteps()
int Parameter::getNumSteps () const override
getText()
juce::String Parameter::getText (float value, int) const override
Referenced by getUserValueText(), and userValueToText().
getValueForText()
float Parameter::getValueForText (const juce::String & text) const override
isOrientationInverted()
bool Parameter::isOrientationInverted () const override
isAutomatable()
bool Parameter::isAutomatable () const override
isMetaParameter()
bool Parameter::isMetaParameter () const override
getSkew()
float Parameter::getSkew ()
References range.
isSkewSymmetric()
bool Parameter::isSkewSymmetric ()
References range.
handleAsyncUpdate()
void Parameter::handleAsyncUpdate () override protected
timerCallback()
void Parameter::timerCallback () override protected
changed()
virtual void Parameter::changed () protected virtual
Member Data Documentation
conversionFunction
std::function<float (float)> Parameter::conversionFunction
Referenced by getProcValue(), and getProcValue().
processor
Processor& Parameter::processor protected
range
const juce::NormalisableRange<float> Parameter::range protected
Referenced by getDefaultValue(), getSkew(), getUserRange(), getUserRangeEnd(), getUserRangeStart(), getUserValue(), getUserValueBool(), getUserValueInt(), getValue(), isOn(), isOnOff(), isSkewSymmetric(), and userValueToText().
internal
bool Parameter::internal = false protected
Referenced by isInternal(), and setInternal().
modMatrix
ModMatrix* Parameter::modMatrix = nullptr protected
Referenced by getModMatrix(), and setModMatrix().
modIndex
int Parameter::modIndex = -1 protected
Referenced by getModIndex(), and setModIndex().
value
std::atomic<float> Parameter::value {0.0f} protected
Referenced by getUserValue(), getUserValueBool(), getUserValueInt(), and getValue().
defaultValue
const float Parameter::defaultValue = 0.0f protected
Referenced by getDefaultValue(), and getUserDefaultValue().
uid
const juce::String Parameter::uid protected
Referenced by getParameterID(), and getUid().
name
const juce::String Parameter::name protected
shortName
const juce::String Parameter::shortName protected
Referenced by getShortName().
label
const juce::String Parameter::label protected
Referenced by getLabel(), getUserValueText(), and userValueToText().
textFunction
const std::function<juce::String (const Parameter&, float)> Parameter::textFunction protected
userActionCount
int Parameter::userActionCount = 0 protected
listeners
juce::ListenerList<ParameterListener> Parameter::listeners protected
The documentation for this class was generated from the following file:
gin_parameter.h