Gin: StandaloneAudioProcessorPlayer Class Reference
StandaloneAudioProcessorPlayer Class Reference
gin_standaloneplugin » standaloneplugin
#include <gin_standaloneaudioprocessorplayer.h>
Inherits gin::AudioProcessorPlayer.
Public Member Functions
StandaloneAudioProcessorPlayer (bool doDoublePrecisionProcessing=false)
void audioDeviceAboutToStart (juce::AudioIODevice *ioDevice) override
void preProcessBlock (juce::AudioBuffer< float > &buffer, juce::MidiBuffer &midi) override
void postProcessBlock (juce::AudioBuffer< float > &buffer, juce::MidiBuffer &) override
void setOutputGain (float gain)
float getOutputGain () const
Public Attributes
AudioFifo scopeFifo
AudioFifo spectrumFifo
AudioFifo xyFifo
AudioFifo recordFifo
MidiFilePlayer midiPlayer
SamplePlayer samplePlayer
AudioRecorder audioRecorder { recordFifo }
StandalonePlayhead playhead
Constructor & Destructor Documentation
StandaloneAudioProcessorPlayer()
StandaloneAudioProcessorPlayer::StandaloneAudioProcessorPlayer (bool doDoublePrecisionProcessing = false)
References midiPlayer, recordFifo, scopeFifo, MidiFilePlayer::setFallbackBpm(), MidiFilePlayer::setLooping(), AudioFifo::setSize(), spectrumFifo, and xyFifo.
Member Function Documentation
audioDeviceAboutToStart()
void StandaloneAudioProcessorPlayer::audioDeviceAboutToStart (juce::AudioIODevice * ioDevice) override
References audioRecorder, midiPlayer, recordFifo, samplePlayer, scopeFifo, SamplePlayer::setPlaybackSampleRate(), MidiFilePlayer::setSampleRate(), AudioRecorder::setSampleRate(), AudioFifo::setSize(), spectrumFifo, and xyFifo.
preProcessBlock()
void StandaloneAudioProcessorPlayer::preProcessBlock (juce::AudioBuffer< float > & buffer, juce::MidiBuffer & midi) override
References MidiFilePlayer::hasFileLoaded(), SamplePlayer::hasFileLoaded(), midiPlayer, playhead, MidiFilePlayer::populatePositionInfo(), SamplePlayer::populatePositionInfo(), MidiFilePlayer::processBlock(), SamplePlayer::processBlock(), samplePlayer, and StandalonePlayhead::setPositionInfo().
postProcessBlock()
void StandaloneAudioProcessorPlayer::postProcessBlock (juce::AudioBuffer< float > & buffer, juce::MidiBuffer &) override
References AudioFifo::getFreeSpace(), recordFifo, scopeFifo, spectrumFifo, AudioFifo::write(), and xyFifo.
setOutputGain()
void StandaloneAudioProcessorPlayer::setOutputGain (float gain)
getOutputGain()
float StandaloneAudioProcessorPlayer::getOutputGain () const
Member Data Documentation
scopeFifo
AudioFifo StandaloneAudioProcessorPlayer::scopeFifo
Referenced by audioDeviceAboutToStart(), postProcessBlock(), and StandaloneAudioProcessorPlayer().
spectrumFifo
AudioFifo StandaloneAudioProcessorPlayer::spectrumFifo
Referenced by audioDeviceAboutToStart(), postProcessBlock(), and StandaloneAudioProcessorPlayer().
xyFifo
AudioFifo StandaloneAudioProcessorPlayer::xyFifo
Referenced by audioDeviceAboutToStart(), postProcessBlock(), and StandaloneAudioProcessorPlayer().
recordFifo
AudioFifo StandaloneAudioProcessorPlayer::recordFifo
Referenced by audioDeviceAboutToStart(), postProcessBlock(), and StandaloneAudioProcessorPlayer().
midiPlayer
MidiFilePlayer StandaloneAudioProcessorPlayer::midiPlayer
Referenced by audioDeviceAboutToStart(), preProcessBlock(), and StandaloneAudioProcessorPlayer().
samplePlayer
SamplePlayer StandaloneAudioProcessorPlayer::samplePlayer
Referenced by audioDeviceAboutToStart(), and preProcessBlock().
audioRecorder
AudioRecorder StandaloneAudioProcessorPlayer::audioRecorder { recordFifo }
Referenced by audioDeviceAboutToStart().
playhead
StandalonePlayhead StandaloneAudioProcessorPlayer::playhead
Referenced by preProcessBlock().
The documentation for this class was generated from the following file:
gin_standaloneaudioprocessorplayer.h