Gin: plugin
plugin
gin_plugin
Macros
#define ProcessorBaseClass juce::AudioProcessor
Functions
float ModVoice::getValue (gin::Parameter *p)
float ModVoice::getValueUnsmoothed (gin::Parameter *p)
Detailed Description
Macro Definition Documentation
ProcessorBaseClass
#define ProcessorBaseClass juce::AudioProcessor
Function Documentation
getValue()
float ModVoice::getValue (gin::Parameter * p)
References ModMatrix::getValue().
Referenced by ModMatrix::getLiveValues().
getValueUnsmoothed()
float ModVoice::getValueUnsmoothed (gin::Parameter * p)
References ModMatrix::getValue().