Gin: components
components
gin_plugin
Namespaces
Resources
Classes
class ADSRComponent
Component for adjuting ADSR curves.
class PowerButton
Circle with line power button for controlling a Parameter.
class ControlBox
A box for holding controls on a grid.
class PagedControlBox
A control for holding pags of controls on a grid Pages slide over top of each other to make room.
class ControlHeader
Just a simple header with a title.
class CopperLookAndFeel
Plugin specific addition to GinLookAndFeel Still black and white.
class CopperLookAndFeelWrapper
Auto sets and clears CopperLookAndFeel as default.
class GateEffectComponent
An editor for the gate effect pattern.
class Knob
Slider + editable text for showing a param.
class LFOComponent
Draws an LFO curve and shows a little dot moving long.
class ModulationSourceButton
A button for enabling modulation learn.
class ModulationDestinationButton
A button for the modulation destination.
class ModulationOverview
A button and text readout that shows the current modulation source.
class ModSrcListBox
A list box of al mod sources.
class ModMatrixBox
A list box of all assigned.
class MultiParamComponent
A base component for controlling multiple parameters at once.
class ParamHeader
A header with optional power button.
class ParamBox
A box for knobs with a header.
class ParamArea
A box for graphs without a header.
class BoxArea
A group of control boxes.
class PatchBrowser
struct PatchBrowser::PresetsModel
struct PatchBrowser::TagsModel
struct PatchBrowser::AuthorsModel
class PluginAlertWindow
An alert window that doesn't add itself to the desktop.
class PluginButton
Button for toggling a parameter.
class PluginComboBox
A control for selecting param values from a dropbox.
class PluginSlider
A slider for controlling a parameter.
class Readout
A control for displaying a parameter.
class ParamComponent
Base class for a control showing a parameter with label.
class HorizontalFader
Horizontal slider wth text for controlling a param.
class Switch
Control for toggling param with label.
class Select
Control for picking param value with label.
class SynthesiserUsage
Control for synth usage.
class UpdateChecker
Checks for plugin updates.
class NewsChecker
Checks Wordpress feed for plugin news.
class ProcessorEditorBase
Base for plugin editor.
class ProcessorEditor
Plugin editor.
class PluginLookAndFeel
Plugin specific addition to GinLookAndFeel Still black and white.
class PluginLookAndFeelWrapper
Auto sets and clears PluginLookAndFeel as default.
class StepLFOComponent
Draws a step LFO curve and shows a little dot moving long.
Functions
void gradientRect (juce::Graphics &g, juce::Rectangle< int > rc, juce::Colour c1, juce::Colour c2)
Detailed Description
Function Documentation
gradientRect()
void gradientRect (juce::Graphics & g, juce::Rectangle< int > rc, juce::Colour c1, juce::Colour c2)
Referenced by ParamBox::addControl(), ParamArea::addControl(), and ParamHeader::ParamHeader().