Gin: components
components
gin
Classes
class ComponentViewer
Shows the component under the mouse and component hierarchy.
class GinLookAndFeel
The GinLookAndFeel.
class MapViewer
Draws an map, etting tiles fom one of many OpenStreetMapsServers.
class PropertyComponentBase
class FilePropertyComponent
class ColourPropertyComponent
class SingleLineTextEditor
An editable text box.
struct SingleLineTextEditor::LookAndFeelMethods
This abstract base class is implemented by LookAndFeel classes to provide TextEditor drawing functionality.
class SingleLineTextEditor::LengthAndCharacterRestriction
An input filter for a TextEditor that limits the length of text and/or the characters that it may contain.
class SingleLineTextEditor::InputFilter
Base class for input filters that can be applied to a TextEditor to restrict the text that can be entered.
class SingleLineTextEditor::Listener
Receives callbacks from a TextEditor component when it changes.
Functions
void addAndMakeVisible (Component &parent, Array< Component *> children)
Adds an Array of components to a parent Component.
void addAndMakeVisible (Component &parent, std::initializer_list< Component *> children)
Adds an std::initializer_list of components to a parent Component.
Detailed Description
Function Documentation
addAndMakeVisible() [1/2]
void addAndMakeVisible (Component & parent, Array< Component *> children)
Adds an Array of components to a parent Component.
Referenced by ControlBox::add(), PagedControlBox::addPage(), ColourPropertyComponent::ColourPropertyComponent(), FilePropertyComponent::FilePropertyComponent(), ProcessorEditorBase::makeResizable(), ModulationOverview::ModulationOverview(), PagedControlBox::PagedControlBox(), PagedControlBox::paramChanged(), PatchBrowser::PatchBrowser(), FilePropertyComponent::refresh(), ModSrcListBox::refreshComponentForRow(), and ModMatrixBox::~ModMatrixBox().
addAndMakeVisible() [2/2]
void addAndMakeVisible (Component & parent, std::initializer_list< Component *> children)
Adds an std::initializer_list of components to a parent Component.