Gin: components
components
gin_gui
Classes
class ComponentGrid
Animated grid container with drag-and-drop reordering support.
struct ComponentGrid::DragInfo
class ComponentViewer
A debugging tool that displays component hierarchy and properties.
class GinLookAndFeel
Minimalist dark look and feel with black background and white controls.
class MapViewer
Interactive map viewer component using OpenStreetMap tiles.
class PropertyComponentBase
Base class for property components that use juce::Value for data binding.
class FilePropertyComponent
Property component for selecting files with a browse button.
class ColourPropertyComponent
Property component for selecting colors with a visual color picker.
class SingleLineTextEditor
An editable text box.
class SingleLineTextEditor::Listener
Receives callbacks from a TextEditor component when it changes.
class SingleLineTextEditor::InputFilter
Base class for input filters that can be applied to a TextEditor to restrict the text that can be entered.
class SingleLineTextEditor::LengthAndCharacterRestriction
An input filter for a TextEditor that limits the length of text and/or the characters that it may contain.
struct SingleLineTextEditor::LookAndFeelMethods
This abstract base class is implemented by LookAndFeel classes to provide TextEditor drawing functionality.
class SVGButton
Button that displays an SVG graphic instead of or alongside text.
Functions
void addAndMakeVisible (juce::Component &parent, juce::Array< juce::Component * > children)
Adds an Array of components to a parent Component.
void addAndMakeVisible (juce::Component &parent, std::initializer_list< juce::Component * > children)
Adds an std::initializer_list of components to a parent Component.
Detailed Description
Function Documentation
addAndMakeVisible() [1/2]
void addAndMakeVisible (juce::Component & parent, juce::Array< juce::Component * > children)
Adds an Array of components to a parent Component.
Referenced by ControlBox::add(), ControlBox::add(), BoxArea::addBox(), BoxArea::addBox(), ParamArea::addControl(), ParamArea::addControl(), ProcessorEditorBase::addControl(), ParamBox::addEnable(), HeaderRow::addItem(), ParamBox::addModSource(), PagedControlBox::addPage(), ColourPropertyComponent::ColourPropertyComponent(), FilePropertyComponent::FilePropertyComponent(), HeaderItem::HeaderItem(), ProcessorEditorBase::makeResizable(), ModulationOverview::ModulationOverview(), PagedControlBox::PagedControlBox(), ParamBox::ParamBox(), and SynthesiserUsage::SynthesiserUsage().
addAndMakeVisible() [2/2]
void addAndMakeVisible (juce::Component & parent, std::initializer_list< juce::Component * > children)
Adds an std::initializer_list of components to a parent Component.