Gin: dsp
dsp
gin_dsp
Classes
class ADSR
Linear ADSR.
class AnalogADSR
Analog ADSR.
class AudioEquationParser
Enhances the EquationParser with math related functions like filters and oscilllators.
class AudioFifo
FIFO - stuff audio in one end and it pops out the other.
struct FuncState
Base class to store an audio functions state But you say "functions don't have state!" Well, that's true, but to make things like filters act as functions, I need to hide a bit of state in them.
struct OscState
State for an oscillator.
struct HP12State
State for high pass filter.
struct HP24State
State for high pass filter.
struct BP12State
State for band pass filter.
struct BP24State
State for band pass filter.
struct LP12State
State for low pass filter.
struct LP24State
State for low pass filter.
struct Notch12State
State for notch filter.
struct Notch24State
State for notch filter.
class AudioFunctionHost
State managment for audio functions.
class GainProcessor
class WetDryMix
Mix between wet and dry with a nice curve.
class BandLimitedLookupTable
Lookup tables for holding bandlimited waveforms.
class BandLimitedLookupTables
Generate and hold bandlimited lookup tabkes for all the common waveforms.
class DelayLine
Audio Delay with linear interpolation.
class Distortion
Distortion based on AirWindows plugins.
class EnvelopeDetector
EnvelopeDetector for Dynamics.
class Dynamics
Compressor / Gate / Expander / Limiter based on algorithm from Designing Audio Effect Plug-ins in C++ by Will Pirkle.
class EasedValueSmoother< T >
Linearly smooths a value in a 0 to 1 range at a constant rate.
class EQ
Basic multi channel / multi band EQ.
class Filter
Basic multi channel filter.
class GateEffect
Gate effect.
class LevelTracker
Track audio levels with decay in dB.
class LFO
LFO with many shapes.
struct LFO::Parameters
class MidiFifo
FIFO - stuff midi in one end and it pops out the other.
class Modulation
Audio modulation, for a chorus or phaser etc.
class StereoOscillator
Stereo oscillator.
struct StereoOscillator::Params
class VoicedStereoOscillator< O >
Stereo Oscillator with multiples voices, pan, spread, detune, etc.
struct VoicedStereoOscillator< O >::Params
class BLLTVoicedStereoOscillator
Stereo Oscillator with multiples voices, pan, spread, detune, etc.
class ResamplingFifo
ResamplingFifo - uses secret rabbit code.
class Sample
Holds an audio sample.
class SampleOscillator
Oscillator for playing samples.
class ScratchBuffer
A temporay buffer provided from a list.
class StepLFO
LFO with editable number of steps.
class StereoDelay
Stereo delay with feedback and cross feedback.
struct GlideInfo
Info on how the voice should glide.
class SynthesiserVoice
A voice with glide info and fast kill support.
class Synthesiser
MPESynthesiser with better fast kill, mono and glide support.
class ValueSmoother< T >
Linearly smooths a value in a 0 to 1 range at a constant rate.
class WTOscillator
WT Oscillator.
struct WTOscillator::Params
class WTVoicedStereoOscillator
Stereo Oscillator with multiples voices, pan, spread, detune, etc.
Enumerations
enum Wave {
Wave::silence = 0, Wave::sine = 1, Wave::triangle = 2, Wave::sawUp = 3,
Wave::sawDown = 4, Wave::pulse = 5, Wave::square = 6, Wave::noise = 7,
Wave::wavetable = 8
}
Functions
juce::Value findValue (juce::ValueTree &state, juce::Identifier name, juce::var value)
template<class T >
T getMidiNoteInHertz (const T noteNumber, const T frequencyOfA=(T) 440.0)
template<class T >
T getMidiNoteFromHertz (const T freq, const T frequencyOfA=(T) 440.0)
float velocityToGain (float velocity, float sensitivity=1.0f)
void applyGain (juce::AudioSampleBuffer &buffer, juce::LinearSmoothedValue< float > &gain)
void applyGain (juce::AudioSampleBuffer &buffer, int channel, juce::LinearSmoothedValue< float > &gain)
void clip (juce::AudioSampleBuffer &buffer, float low=-1.0f, float high=1.0f)
juce::String getMidiMessageType (const juce::MidiMessage &msg)
juce::AudioSampleBuffer sliceBuffer (juce::AudioSampleBuffer &input, int start, int length)
Get a section of an audio buffer.
double sine (double phase, double unused1=0, double unused2=0)
double triangle (double phase, double freq, double sampleRate)
double sawUp (double phase, double freq, double sampleRate)
double sawDown (double phase, double freq, double sampleRate)
double pulse (double phase, double pw, double freq, double sampleRate)
double squareWave (double phase, double freq, double sampleRate)
double noise ()
bool loadWavetables (juce::OwnedArray< BandLimitedLookupTable > &bllt, juce::AudioSampleBuffer &buffer, double sampleRate, int tableSize)
Variables
constexpr float Q = 0.70710678118655f
Detailed Description
Enumeration Type Documentation
Wave
enum Wave strong
Enumerator
silence
sine
triangle
sawUp
sawDown
pulse
square
noise
wavetable
Function Documentation
findValue()
juce::Value findValue (juce::ValueTree & state, juce::Identifier name, juce::var value)
getMidiNoteInHertz()
template<class T > T getMidiNoteInHertz (const T noteNumber, const T frequencyOfA = (T)440.0)
Referenced by OscState::incPhase(), and BandLimitedLookupTable::reset().
getMidiNoteFromHertz()
template<class T > T getMidiNoteFromHertz (const T freq, const T frequencyOfA = (T)440.0)
velocityToGain()
float velocityToGain (float velocity, float sensitivity = 1.0f)
References applyGain(), and clip().
applyGain() [1/2]
void applyGain (juce::AudioSampleBuffer & buffer, juce::LinearSmoothedValue< float > & gain)
Referenced by velocityToGain().
applyGain() [2/2]
void applyGain (juce::AudioSampleBuffer & buffer, int channel, juce::LinearSmoothedValue< float > & gain)
clip()
void clip (juce::AudioSampleBuffer & buffer, float low = -1.0f, float high = 1.0f)
Referenced by velocityToGain().
getMidiMessageType()
juce::String getMidiMessageType (const juce::MidiMessage & msg)
Referenced by GainProcessor::process().
sliceBuffer()
juce::AudioSampleBuffer sliceBuffer (juce::AudioSampleBuffer & input, int start, int length)
Get a section of an audio buffer.
sine()
double sine (double phase, double unused1 = 0, double unused2 = 0)
triangle()
double triangle (double phase, double freq, double sampleRate)
sawUp()
double sawUp (double phase, double freq, double sampleRate)
sawDown()
double sawDown (double phase, double freq, double sampleRate)
pulse()
double pulse (double phase, double pw, double freq, double sampleRate)
squareWave()
double squareWave (double phase, double freq, double sampleRate)
noise()
double noise ()
loadWavetables()
bool loadWavetables (juce::OwnedArray< BandLimitedLookupTable > & bllt, juce::AudioSampleBuffer & buffer, double sampleRate, int tableSize)
Referenced by WTVoicedStereoOscillator::setWavetable().
Variable Documentation
Q
constexpr float Q = 0.70710678118655f
Referenced by HP24State::process(), BP24State::process(), LP24State::process(), Notch24State::process(), and Filter::setParams().