Gin: SingleLineTextEditor::LookAndFeelMethods Struct Reference
SingleLineTextEditor::LookAndFeelMethods Struct Reference abstract
gin » components
This abstract base class is implemented by LookAndFeel classes to provide TextEditor drawing functionality.
Public Member Functions
virtual ~LookAndFeelMethods ()
virtual void fillSingleLineTextEditorBackground (Graphics &, int width, int height, SingleLineTextEditor &)=0
virtual void drawSingleLineTextEditorOutline (Graphics &, int width, int height, SingleLineTextEditor &)=0
virtual CaretComponent * createSingleLineCaretComponent (Component *keyFocusOwner)=0
Detailed Description
This abstract base class is implemented by LookAndFeel classes to provide TextEditor drawing functionality.
Constructor & Destructor Documentation
~LookAndFeelMethods()
virtual SingleLineTextEditor::LookAndFeelMethods::~LookAndFeelMethods () virtual
References SingleLineTextEditor::colourChanged(), SingleLineTextEditor::enablementChanged(), SingleLineTextEditor::focusGained(), SingleLineTextEditor::focusLost(), SingleLineTextEditor::isTextInputActive(), SingleLineTextEditor::keyPressed(), SingleLineTextEditor::keyStateChanged(), SingleLineTextEditor::lookAndFeelChanged(), SingleLineTextEditor::mouseDoubleClick(), SingleLineTextEditor::mouseDown(), SingleLineTextEditor::mouseDrag(), SingleLineTextEditor::mouseUp(), SingleLineTextEditor::mouseWheelMove(), SingleLineTextEditor::paint(), SingleLineTextEditor::paintOverChildren(), SingleLineTextEditor::resized(), and SingleLineTextEditor::setTemporaryUnderlining().
Member Function Documentation
fillSingleLineTextEditorBackground()
virtual void SingleLineTextEditor::LookAndFeelMethods::fillSingleLineTextEditorBackground (Graphics & , int width, int height, SingleLineTextEditor &) pure virtual
drawSingleLineTextEditorOutline()
virtual void SingleLineTextEditor::LookAndFeelMethods::drawSingleLineTextEditorOutline (Graphics & , int width, int height, SingleLineTextEditor &) pure virtual
createSingleLineCaretComponent()
virtual CaretComponent* SingleLineTextEditor::LookAndFeelMethods::createSingleLineCaretComponent (Component * keyFocusOwner) pure virtual
The documentation for this struct was generated from the following file:
gin_singlelinetexteditor.h