#!/bin/sh -e
set -x

OS=linux
export GDK_BACKEND=x11

ROOT=$(cd "$(dirname "$0")/../.."; pwd)
cd "$ROOT"

sudo apt-get update
sudo apt-get install clang git ladspa-sdk freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev webkit2gtk-4.0 juce-tools xvfb

Xvfb :99 &
export DISPLAY=:99
sleep 5

if [ ! -d "juce" ]; then
  git clone https://github.com/WeAreROLI/JUCE.git --branch develop --single-branch juce
fi

# Get the hash
cd "$ROOT/juce"
HASH=`git rev-parse HEAD`
echo "Hash: $HASH"

# Get the Projucer
mkdir -p "$ROOT/ci/bin"
cd "$ROOT/ci/bin"
while true
do
  PROJUCER_URL=$(curl -s -S "https://projucer.rabien.com/get_projucer.php?hash=$HASH&os=$OS&key=$APIKEY")
  echo "Response: $PROJUCER_URL"
  if [ "${PROJUCER_URL:0:4}" == "http" ]; then
    curl -s -S $PROJUCER_URL -o "$ROOT/ci/bin/Projucer.zip"
    unzip Projucer.zip
    break
  fi
  sleep 15
done

"$ROOT/ci/bin/Projucer" --set-global-search-path linux  defaultJuceModulePath "$ROOT/juce/modules" 
"$ROOT/ci/bin/Projucer" --resave "$ROOT/examples/Demo/Demo.jucer"

cd "$ROOT/examples/Demo/Builds/LinuxMakefile"
make CONFIG=Release

rm -Rf "$ROOT/ci/linux/bin"
mkdir -p "$ROOT/ci/linux/bin"
cp -R "$ROOT/examples/Demo/Builds/LinuxMakefile/build/Demo" "$ROOT/ci/linux/bin"

cd "$ROOT/ci/linux/bin"
zip -r Demo.zip Demo

rm -Rf Demo
