/*==============================================================================

 Copyright (c) 2018 - 2026 by Roland Rabien.
 For more information visit www.rabiensoftware.com

 ==============================================================================*/

#pragma once

/**
    Reads EXIF (Exchangeable Image File Format) metadata from JPEG images.

    ExifMetadata extracts camera and image information embedded in JPEG files,
    including camera settings, GPS coordinates, timestamps, and technical details.
    EXIF data is commonly generated by digital cameras and smartphones.

    Key Features:
    - Camera settings (ISO, aperture, shutter speed, focal length)
    - GPS coordinates and altitude
    - Date/time information
    - Camera make and model
    - Thumbnail image extraction
    - Orientation information

    Common EXIF tags include:
    - Make, Model: Camera manufacturer and model
    - DateTime: When photo was taken
    - ExposureTime: Shutter speed
    - FNumber: Aperture (f-stop)
    - ISOSpeedRatings: ISO sensitivity
    - FocalLength: Lens focal length
    - GPSLatitude, GPSLongitude: Location data

    Usage:
    @code
    FileInputStream stream(jpegFile);
    OwnedArray<ImageMetadata> metadata;
    ImageMetadata::getFromImage(stream, metadata);

    for (auto* meta : metadata)
    {
        if (auto* exif = dynamic_cast<ExifMetadata*>(meta))
        {
            StringPairArray data = exif->getAllMetadata();
            String camera = data["Make"] + " " + data["Model"];
            String dateTime = data["DateTime"];
            Image thumbnail = exif->getThumbnailImage();
        }
    }
    @endcode

    @see ImageMetadata, XmpMetadata
*/
class ExifMetadata : public ImageMetadata
{
public:
    ExifMetadata();
    virtual ~ExifMetadata();

    static ExifMetadata* create (const juce::uint8* data, int sz);

    juce::StringPairArray getAllMetadata() const;

    juce::Image getThumbnailImage();

private:
    static int sizeofType (int type);

    struct MetadataItem
    {
        ~MetadataItem();

        int tag;
        int type;
        int count;
        int section;
        bool bigEndian;
        void* data = nullptr;

        juce::String getName() const;
        juce::String getValue() const;

        juce::uint16 swap16 (juce::uint16 a) const;
        juce::int16 swap16 (juce::int16 a) const;
        juce::uint32 swap32 (juce::uint32 a) const;
        juce::int32 swap32 (juce::int32 a) const;
    };

    struct MetadataSection
    {
        MetadataSection (int id_, int offset_) { id = id_; offset = offset_; }

        int id;
        int offset;
    };

    juce::OwnedArray<MetadataItem> items;
    char* thumbImg = nullptr;
    int thumbNumBytes = 0;
};
